### ISSUE TITLE
Clothes dryer

### ISSUE THREAD

**Issue by iteles** [dwyl/home#103]
For rainy days and to avoid great displays of clothes hanging everywhere, we'll need to have an energy efficient clothes dryer.

## Machine Type
There are three main types of dryers:
+ **Exaustão:** These chuck out all of their steam, so a tube is necessary to carry the steam out of the dryer and to the exterior. We have this set-up should we need it.
+ **Condensação:** These collect all of the water in a recipient within the machine itself which needs to be emptied regularly. Although it means they can be installed anywhere without needing a tube to allow steam out into the world, for our purposes, it's worth going for something else to avoid the additional task of emptying this out.
+ **Bomba de calor:** These tend to be the most energy-efficient, [most delicate with clothes](https://www.worten.pt/dicas-para-escolher-maquinas-secar-roupa) and less noisy ones on the market. There is always a small water deposit to empty out but for the above, **We will go for a heat pump type machine**.

## Size

At this stage we have a 12kg washing machine (although we also intend to have a smaller one) so the main question is whether we will also need a dryer that accommodates this load?

+ **10kg**: These exist but there is _very_ little choice in them and honestly, if we can't get a full load in them anyway, it makes no sense. We'll either have too many clothes for a full load (12kg washing machine) or too few (8-9kg washing machine) so it would be silly to limit our choices like this and it would likely end up being much less eco-friendly because of the load mismatch.
+ **9kg**: There isn't a HUGE amount of choice here but it would be good to get a 9kg machine. This depends a little on the size of the small washing machine we end up getting.
+ **8kg**: This is a good size and we wouldn't go any smaller than this. If we get a 9kg washing machine, this wouldn't be feasible.

**Comment by iteles** [comment]
I have had a look through the Black Friday sales and they are thin on the ground for dryers.

The following have nothing of interest because I have discounted SMEG machines which might be good now, but would be harder to maintain in the long run (less people qualified to fix them/less parts available):
+ Worten
+ Fnac
+ Rosalar


Each of El Corte Ingles and Media Markt only had one option worth considering (below).


# 9kg

## AEG T8DEE942
+ **Class**: A++
+ **Size:** 9kg
+ **Noise level:** 65dB
+ **Average annual energy consumption:** 259kWh
+ **Ease of use**: 1 knob + LCD screen options
+ **Price:** €599 (+€20 shipping)

https://www.elcorteingles.pt/electrodomesticos/A19862629-maquina-de-secar-de-condensacao-t8dee942-com-bomba-de-calor-a/
![image](https://user-images.githubusercontent.com/4185328/69914096-02727100-1438-11ea-9e8d-7015d13556e2.png)


#8kg 

## AEG T7DBK841Z
+ **Class**: A++
+ **Size:** 8kg
+ **Noise level:** 66dB
+ **Average annual energy consumption:** 235kWh
+ **Ease of use**: 1 knob + LCD screen options
+ **Price:** €499

https://mediamarkt.pt/collections/grandes-eletrodomesticos-u/products/aeg-maquina-secar-roupa-t7dbk841z-8kg-classe-a
![image](https://user-images.githubusercontent.com/4185328/69914010-15387600-1437-11ea-8d58-4b021471c380.png)

## Conclusion
These AEG deals are actually pretty worth it. 

I've had a look through machines in general and **for the A++ energy efficiency category** these are are good brand, with good noise levels and they would be great options.

**Not worth researching any further for A++ energy ratings**.

I will spend a quick pomodoro on A+++ ones to see if any are worth it (but there are **none on BF deals** so we could just buy these in January).

**Comment by nelsonic** [comment]
@iteles as discussed verbally, totes agree with opting for a heat pump machine type for energy efficiency.

There is actually a surprisingly decent amount of choice in the 10kg size:
https://www.johnlewis.com/browse/electricals/washing-machines-tumble-dryers/tumble-dryers/10kg/_/N-afdZ1z0fiea
e.g:  https://www.johnlewis.com/hoover-atd-hy10a2kex-80-freestanding-heat-pump-tumble-dryer-10kg-load-a-energy-rating-white/p3859163
![image](https://user-images.githubusercontent.com/194400/69914043-82e4a200-1437-11ea-962b-34ce2dbab8d1.png)

Sadly, _everything_ home appliance is more expensive in PT:
https://mediamarkt.pt/products/hoover-maquina-secar-roupa-10kg-atd-hy10a2tkex-s?variant=30284778930219
![image](https://user-images.githubusercontent.com/194400/69914064-bc1d1200-1437-11ea-8b94-8e86aae7d744.png)

I think the "Black Friday" deals aren't _especially_ great this year, 
MediaMarkt only has _two_ dryers discounted and they are both 8KG models:
<img width="1160" alt="mediamarkt-black-friday-clothes-dryers" src="https://user-images.githubusercontent.com/194400/69914157-c55aae80-1438-11ea-9553-0e2804ee00a0.png">

https://mediamarkt.pt/collections/bulky/products/aeg-maquina-secar-roupa-t7dbk841z-8kg-classe-a
![image](https://user-images.githubusercontent.com/194400/69914127-66953500-1438-11ea-9caf-9360b90f357d.png)

Similar story on Worten https://www.worten.pt/grandes-eletrodomesticos/maquinas-de-roupa
<img width="1248" alt="worten-black-friday-secar" src="https://user-images.githubusercontent.com/194400/69914191-22566480-1439-11ea-8a71-015998e47e9c.png">

The company/site we bought the _mega_ washing machine from last year:
https://www.euronics.pt/pt/maquinas-de-roupa/maquinas-de-secar-roupa_387-378.html&p=1&ft=c2VtZXN0cmV8fDY1
does not have any particularly amazing deals on this year ... the best one is this 9KG indesit for €445:
https://www.euronics.pt/pt/a+/maquinas-de-secar/maquina-de-secar-roupa-indesit-yt-m10-91-r-eu/item_7912.html?id=387&cat=378&pc=1
![image](https://user-images.githubusercontent.com/194400/69914233-a7da1480-1439-11ea-931e-f37051dc8e30.png)
The only _disadvantage_ being the energy efficiency rating of (_only_) "A+"

**Comment by iteles** [comment]
@nelsonic I genuinely think that a 10kg machine makes no sense because we would always have an unoptimised load, so it would be way less energy efficient than other machines.

For the Indesit one, I'd rather get the [Hoover A++ one I mentioned above](https://github.com/dwyl/home/issues/103#issuecomment-560104283).

## A+++ machines

Honestly, they are all exorbitant. 

These are the only good-ish deals I found:

### BOSCH WTR87641ES
+ **Class**: A+++
+ **Size:** 8kg
+ **Noise level:** 64dB
+ **Average annual energy consumption:** 176kWh
+ **Ease of use**: 1 knob
 **Price:** €615

https://redprice.pt/product/maquina-de-secar-roupa-bosch-wtr87641es
![image](https://user-images.githubusercontent.com/4185328/69914603-fa1d3480-143d-11ea-9c55-13f59cc25e18.png)

## SMEG DHT83LIN
+ **Class**: A+++
+ **Size:** 8kg
+ **Noise level:** 65dB
+ **Average annual energy consumption:** 176kWh
+ **Ease of use**: 1 knob
 **Price:** €679

https://mediamarkt.pt/collections/maquinas-de-secar-roupa-sc/products/maquina-secar-roupa-dht83lin
![image](https://user-images.githubusercontent.com/4185328/69914279-52eace00-143a-11ea-8d05-ae4991ed5f42.png)

**Comment by iteles** [comment]
I'm leaning towards the 9kg Hoover on promotion in https://github.com/dwyl/home/issues/103#issuecomment-560104283

**Comment by nelsonic** [comment]
@iteles it's worth noting that energy efficiency of the Bosch will pay for the difference in price in a couple of years if we assume the machine gets used once per day ...

The stated energy efficiency for the two machines I would most consider 
176kWh/year (8kg Bosch €603) vs. 259kWh/year (9kg Hoover €445)
259 - 176 = 83kWh/year 
83 x €0.19 = €15.77/year ... (603 - 445)/15.77 = 10 years.

_But_ ... I think we will have _considerably_ more use than the "_average_" family/user because there are a lot more people in our house than an average family ...

The Hoover consumes 2,18 kWh per drying cycle and takes 260 min ... **4.3 hours** 😮 
![image](https://user-images.githubusercontent.com/194400/69914991-073c2280-1442-11ea-8262-e10549a42bc0.png)
whereas the Bosh uses 1.4kWh and takes  159mins per cycle ... **2.65 hours**
![image](https://user-images.githubusercontent.com/194400/69915009-35216700-1442-11ea-8438-dd4b7cfc1bfb.png)

With 30 people in the house I'd expect the dryer to be used once per day.
If we assume that the slower less energy efficient machine uses 1kWh more energy per load
that would be 365 days x €0.19 = €69.35/year
Payback: (603 - 445)/69.35 = 2.27 years.
Ideally we could use our Solar energy to power all the appliances in the house.
But at peak usage our 10kW of solar will be consumed pretty quickly by AirCon, Kitchen appliances, etc.
So we _must_ count on spending _some_ money on EDP (electricity company) units ...

Worth considering. 💭

**Comment by iteles** [comment]
4 hours?! No thank you. 

The AEG machine looks like it has a standard duration of 136 minutes (though I couldn't find any information on the AEG website so it seems like it might be a pretty old model?): https://www.pccomponentes.com/aeg-t7dbk841z-secadora-bomba-de-calor-de-carga-frontal-8kg-a-blanca

I think the decision is between the Bosch A+++ at €605 and the AEG A++ at €499.

**Comment by nelsonic** [comment]
@iteles indeed. 4h is a _long_ time to wait ... even if it's a "set and forget", it's _ages_! ⏳😧 
I'd go with the Bosch as noted above the energy efficiency benefit outweighs the up-front cost. 💰⚖️⚡️

**Comment by iteles** [comment]
Paid for and delivery delayed until January, when we'll need to call to schedule the delivery.

**Comment by iteles** [comment]
Arrived today #105 🙌
