### ISSUE TITLE
White goods arriving next week

### ISSUE THREAD

**Issue by iteles** [dwyl/home#105]
The following white goods are arriving Monday 13-Jan-2020:
+ 2 x fridges from Worten #80 
+ Small washing machine from Worten
+ Large washing machine from Rosalar
+ Clothes dryer from Redprice #103 (this _may_ be delayed until Tuesday depending on the transporter, TBC)

I _believe_ the Worten people will _install_ the washing machine (and fridges) but I am waiting for final word on this. All the others are just transporting companies but will drop the machines off in our kitchen.

**Comment by nelsonic** [comment]
I'll be here when everything arrives. 👍 
It's going to be _amaze_ to have a fridge. 
I've been using the local super market as my fridge and it's a bit tedious ... 🙄 `#firstworldproblems`

**Comment by iteles** [comment]
So will I of course. Very excited about this.

Also, let's keep some of the packaging these things come in to use as temporary tables and storage whilst we're building the furniture before we recycle them 😊

**Comment by iteles** [comment]
All arrived today 👍
