### ISSUE TITLE
Nap pods in London £18/h 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#11]
https://www.standard.co.uk/news/london/exhausted-new-parents-turning-to-nap-pods-in-london-in-order-to-catch-up-on-sleep-a3926981.html
Does anyone else see any issue with this...? 😕
![image](https://user-images.githubusercontent.com/194400/45269051-c3e14700-b47e-11e8-9019-4112efe929ac.png)

Besides the fact that this "article" is _blatantly_ ["Advertorial"](https://en.wikipedia.org/wiki/Advertorial) ... 🙄

**Comment by iteles** [comment]
£18 an HOUR?! Way to take advantage of people's exhaustion (i.e. debilitated state). 😕

**Comment by nelsonic** [comment]
Yeah, most people in London (_outside of the Tech/Finance "bubble"_) don't _earn_ £18/hour ... 😖 
Which _explains_ why they are based in Old Street: 🙄 

> "Pop & Rest opened as a pop-up in Monument last year, then set up a permanent base near Old Street in June due to a surge in demand for its rooms."

I'm not _against_ napping during the day in fact I'm a _fan_ of the idea if I've had a poor night's sleep the night before for any reason ... 

In Japan there is a culture of time-boxed sleep which many claim boosts productivity:

# [hirune](https://en.wiktionary.org/wiki/%E6%98%BC%E5%AF%9D) or [inemuri](https://en.wikipedia.org/wiki/Sleeping_while_on_duty)

http://www.bbc.com/future/story/20160506-the-japanese-art-of-not-sleeping
http://www.openculture.com/2017/12/inemuri-the-japanese-art-of-taking-power-naps-at-work-on-the-subway-and-other-public-places.html

[![image](https://user-images.githubusercontent.com/194400/45269014-238b2280-b47e-11e8-8ba6-0958b7e38959.png)](https://youtu.be/KuZXY5FwHUg)
https://youtu.be/KuZXY5FwHUg

[![image](https://user-images.githubusercontent.com/194400/45268424-f9ccfe00-b473-11e8-8da1-234ef0571efd.png)](https://youtu.be/S0-oNv51j9o)
https://youtu.be/S0-oNv51j9o

What I _object_ to is the fact that London Lifestyle is "burning people out".
"New Parents" should not _have_ to be rushing back to work.
Obviously, if they _chose_ to use this service it's _good_ that it _exists_.
The prices is more a factor of "Supply and Demand" and due to _location_ than anything else.
This is a "patch" on a problem rather than addressing the "root cause".

**Comment by stefek99** [comment]
The other day the only place I could find to have a nap was a disabled toilet in the office.

I need to find a better way of recharging, rather than ingesting stimulants (such as coffee)

**Comment by stefek99** [comment]
Little tangent.

Language concept: "work life balance"

For me it is: "life work balance" (putting life first) or "life work integration"

**Work should not be different from life?**

Preaching to the quire now, I'm hoping to connect with you either in London or in Portugal...

**Comment by nelsonic** [comment]
Closing as not actionable. 📕 
Would have been good to do a research trip to investigate their facilities, comfort and _cleanability_. 🔍 
But ultimately common sense will dictate what we do @home. 👌
