### ISSUE TITLE
Cheapest Travel from Lisbon to Braga?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#115]
There are 3 ways to travel from Lisbon to Braga.

## _Fastest_ 🚅 `€34.20` 3h 30m

If money is no object and you want the fastest journey, the _best_ option is the "Alpha Pendular" Train.
The train departs from Lisboa Santa Apolónia - Av. Infante Dom Henrique 1, 1100-105 Lisboa
https://goo.gl/maps/D7yPP29ULTTyb58m8
Timetable: https://www.cp.pt/passageiros/pt/consultar-horarios
Prices: https://www.cp.pt/StaticFiles/Passageiros/1_horarios/precos/ap/precos-alfa-pendular-lisboa-porto-braga-guimaraes.pdf

The train is obviously our _favourite_ mens of transport because the ride is smooth and linear. 
All chairs have fold-down tables which fit a laptop and it's easy to get work done, read or sleep.
If you _know_ you are going to be _returning_ by train then the round trip (_both journeys_) is **`€55`**

## _Mid-priced_ 🚌 `€20.90` 4h 30mins

The _second_ cheapest mode of transport is the bus. **`€22.88` 4h 30mins**
 https://www.rede-expressos.pt (_official_)
![image](https://user-images.githubusercontent.com/194400/73689032-3b8fc180-46c5-11ea-9132-da3417decac6.png)

This bus departs from Terminal Rodoviário Sete Rios., 1500, R. Prof. Lima Basto 133, Lisboa
https://goo.gl/maps/hgD69TWeDpvuj7Fg7
Most people visiting/staying in Lisbon will _not_ be near Sete Rios.
So will need to factor in at _least_ **`€1.50`** of Metro (_or Bus/Train_) journey 
from wherever they are to Sete Rios. 

The bus is comfortable and _direct_. 
The bus terminal in Braga is a 10 min walk from @home 🚶‍♀ 

## _Cheapest_ 🚌 + 🚋  **`€10.79` 6 hours**

The _cheapest_ way to get from Lisbon to Braga requires 3 separate journeys.
To get the _cheapest_ bus price (stage 2) you should book a couple of days in advance as noted by @iteles below https://github.com/dwyl/home/issues/115#issuecomment-581827372

1. **Train** from Lisbon to Cascais (_or Sintra_) **`€2.25` 40mins**
https://www.cp.pt/StaticFiles/horarios/urbanos-lisboa/comboios-urbanos-lisboa-cascais.pdf

2. **Bus** from Cascais (_or Sintra_) to Porto **`€5.29` 3h 50mins** departs **07:00**, **13:00** or **19:00**
https://royalexpress.com/st_activity/expresso-cascais-porto the Bus costs more if you buy the ticket the day before or on the day of travel, so _prepare_ your journey and book a few days in advance!
![image](https://user-images.githubusercontent.com/194400/73687435-eef6b700-46c1-11ea-95dd-ca0cddc48a1a.png)
The "Royal Express" Bus arrives at:  Garagem Atlântico, R. de Alexandre Herculano, 4000-053 Porto
https://goo.gl/maps/2WrBCHAVHfpP4ArT6

3. **Walk** from Porto **Bus Station** to Porto (São Bento) **Train Station** **`FREE` 7 mins**. 
It's a pleasant walk, all down hill and only takes **7 mins** ... if you don't have heavy bags, walk. 🚶 

https://goo.gl/maps/2WrBCHAVHfpP4ArT6
![image](https://user-images.githubusercontent.com/194400/73736252-60714c80-4738-11ea-9928-e8c6c1ad5de8.png)

4. **Train** from Porto to Braga **`€3.25` 49mins**
Timetable: https://www.cp.pt/StaticFiles/horarios/urbanos-porto/comboios-urbanos-porto-braga.pdf
Prices: https://www.cp.pt/StaticFiles/Passageiros/1_horarios/precos/pt/preco-por-zona-comboios-urbanos-porto.pdf

This is definitely the "_scenic_ route".
If you are already in Cascais or on the Coast for whatever reason, (_e.g: your family lives there..._)
this journey ends up being _faster_ than going into Lisbon to catch the Bus or Train.
It's just a question of timing as there are only 3 departure times from Cascais each day 7am, 1pm & 7pm.

@iteles took this journey option last year from Cascais to Braga and says it was "fine". 👍 

@edwardcodes / @miguelmartins17 have you considered the "Royal Express" option? 💭 
For you guys it would be **`€10`** from Carcavelos to Braga in around 5.5h. 💡

**Comment by iteles** [comment]
@nelsonic In Porto you’d head to estação de S. Bento which is a 7 minute _downhill_ walk from the bus stop rather than 25mins to Campanhã 😊
![08EF77F2-5F98-4C48-8E93-5FD198CAD43D](https://user-images.githubusercontent.com/4185328/73733406-cd361800-4733-11ea-952c-1f8c151d6c01.jpeg)

**Comment by nelsonic** [comment]
@iteles thanks for the insight into walking to São Bento instead of Campanhã. 👍 (_updated above_)
and confirming that the ticket price is still the €5.29 (_bargain!_) if booked a couple of days in advance. 💡

**Comment by edwardcodes** [comment]
@nelsonic @iteles I took the Train Alfa Pendular in St Apolónia to Braga 3:30h for 34,90€ but with the youth discount it’s 26€.
It’s not cheap but it’s a good option!

**Comment by nelsonic** [comment]
@edwardcodes `#YouthDiscount` indeed. 😜 Safe journey today.

**Comment by nelsonic** [comment]
Closing as no longer relevant. "ghost" indeed. 👌
