### ISSUE TITLE
Kitchen | Undercounter lighting

### ISSUE THREAD

**Issue by iteles** [dwyl/home#12]
Undercounter lighting in the kitchen is super important as cupboards and shelves often create shadows on counters which can lead to people cutting themselves or to badly washed crockery!

Our undercounter lighting at our house failed so I thought I'd catalogue some of the research here for future reference.

Starting with Ikea options:
+ LED strip (or from Ikea: https://www.ikea.com/gb/en/products/lighting/integrated-lighting/omlopp-led-worktop-lighting-white-art-10245224/)
+ More Ikea LED spotlights: https://www.ikea.com/gb/en/products/lighting/integrated-lighting/ledberg-led-spotlight-white-art-70400924/
![image](https://user-images.githubusercontent.com/4185328/45925154-13585600-bf08-11e8-83fb-ce58261123a5.png)
+ Slightly brighter but also more expensive ones which we can also install without an electrician: https://www.ikea.com/gb/en/products/lighting/integrated-lighting/omlopp-led-spotlight-white-art-70245179/
![image](https://user-images.githubusercontent.com/4185328/45925166-439ff480-bf08-11e8-854a-b911ef9c4c61.png)

**Comment by iteles** [comment]
I am _always_ taken in by bright and easy lighting.

Came across this and whilst this Davy guy speaking in the video is all about the drama, (the title of 'Senior Vice President' of anything is 🙄), the product itself is interesting!

I wonder if they'll make the pricing more accessible once they get out of their first run phase.
https://www.kickstarter.com/projects/667671899/luminook-big-light-for-small-spaces?

![image](https://user-images.githubusercontent.com/4185328/73120913-cc4efa80-3f6b-11ea-9845-841f3a46dedc.png)

**Comment by nelsonic** [comment]
@iteles we will be building a _similar_ solution using ultra-low cost (_but secure_) open source hardware and publishing the schematics so that _anyone_ can use them. This will be integrated into all the bunk beds and storage for the attic rooms. 👍

**Comment by iteles** [comment]
That's also where my mind went with the accessibility question 😊

**Comment by iteles** [comment]
We settled on IRSTA lighting for now with dimmable panels to give people that perfect lighting for videos.

https://www.ikea.com/pt/pt/p/irsta-iluminacao-led-p-bancada-branco-opala-10406943/
<img width="1449" alt="image" src="https://user-images.githubusercontent.com/4185328/162232966-d0f02cb0-acc0-4926-b43d-4378e3cc1f08.png">

I need to get these ordered asap 👍

**Comment by nelsonic** [comment]
These lights would have been _epic_ but they were discontinued by IKEA and out-of-stock when we tried to order ... 🤦‍♂️ 
So we went with more basic LED strips. 💡
