### ISSUE TITLE
Bathroom / Shower Division Layout

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#127]
At bathrooms are ready for finalising with divisions:
![4F2A3943-C2D9-4A29-9866-38B3EEC6E165](https://user-images.githubusercontent.com/194400/85696146-93f54900-b6d0-11ea-872b-d9f81db317fa.jpeg)
![829A1856-4A4B-49FA-9F8F-1BC983C3A08E](https://user-images.githubusercontent.com/194400/85696153-95bf0c80-b6d0-11ea-8bac-6aa3e6036d91.jpeg)
![49198B46-B44D-44C2-A854-E7C63439426D](https://user-images.githubusercontent.com/194400/85696156-9657a300-b6d0-11ea-96a8-4edf2affac28.jpeg)
![47F48FEF-C89E-4488-B1F4-37484364832C](https://user-images.githubusercontent.com/194400/85696161-9788d000-b6d0-11ea-87ff-6b5db57c2d79.jpeg)

# Todo

+ [x] take detailed measurements and create floor map “as is” for each bathroom/shower
+ [x] create “fenolico” layout for each shower stall

My plan is to do all of this in Inkscape because it’s just 2D work and I need to practice my *Open Source* graphics skills.

**Comment by iteles** [comment]
@nelsonic As I mentioned in #126, I have all these measurements in a rough hand-drawn floor plan on my iPad. I am _happy_ to dedicate time today to learning Inkscape and getting these into a portable format for use when we pair on the phenolic door designs.

**Comment by nelsonic** [comment]
@iteles, if you want to download + install Inkscape https://inkscape.org/release on your Mac 
and Create a File for each room in `.svg` using the room dimensions as the canvas size
and then drawing in all the relevant items into the layout,
please go for it. 

For _example_ the _west_ shower stall in the basement is 1415mm x 880mm  

![shower-stall-measurements](https://user-images.githubusercontent.com/194400/85703214-0d903580-b6d7-11ea-969b-c87d09e80fed.jpeg)

So the Document Properties in Inkscape have to match this _internal_ dimension.
I think it makes sense to add **10mm** of "breathing" room around the layout on 
so I made the document 900mm x 1435mm:

![basement-west-shower-inkscape-document-properties-with-space](https://user-images.githubusercontent.com/194400/85710355-159fa380-b6de-11ea-8f96-97df90edb5e8.png)

Inkscape is reasonably straightforward to use, but there are a few "gotchas" specifically Paths vs. Objects. 🤦 
see:

[![image](https://user-images.githubusercontent.com/194400/85710487-3667f900-b6de-11ea-9599-8eea7f996a03.png)](https://youtu.be/p67XVtX07eM)
https://youtu.be/p67XVtX07eM

Also, while Inkscape has a good array of keyboard shortcuts: https://inkscape.org/doc/keys.html
it's still designed to be used with a mouse. Your "productivity" will suffer with just a trackpad.

I was planning on doing all the _existing_ outlines in black with labels in PT in grey.
I'm _very_ happy to _pair_ on this at the Standing Desk in the Studio.

**Comment by nelsonic** [comment]
@iteles I've done an _example_ in Inkscape for the _west_ basement shower/stall:

![inkscape-shower-layout](https://user-images.githubusercontent.com/194400/85717804-c9f0f800-b6e5-11ea-9f88-09567dc9b561.png)

The beauty of using _open_ formats like `.svg` is that GitHub can track history and show the changes in the browser:
https://github.com/dwyl/home/blob/master/bathrooms/braga-home-basement-west-shower-stall.svg

![image](https://user-images.githubusercontent.com/194400/85717932-ed1ba780-b6e5-11ea-9442-5b65cbe62772.png)

While Inkscape is _definitely_ not an "architectural" CAD program, I think it's _perfect_ for these 2D vectors.
If we can make them all _similar_ then it will look "***totes profesh***" when we hand them over to the carpenters for cutting.
(_this morning when the carpenter visited the site he had very "scribbly" sketches for his measurements ..._)

I just tested printing on the **Epson ET-2600** and it appears to not be printing any of the _colors_:
![braga-west-shower-dimensions-printed](https://user-images.githubusercontent.com/194400/85721250-1ab62000-b6e9-11ea-98f2-4c505f021d30.jpeg)

But this is probably enough info for them to go on ...
(_I'm going to investigate the printer issue, but definitely not "urgent"_)

**Comment by nelsonic** [comment]
Layouts complete: https://github.com/dwyl/home/tree/master/bathrooms
