### ISSUE TITLE
Label Printer

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#135]
I'm _very_ keen to have as many things labeled (_preferably with both text and a QR code_) as possible so that I can organise things. We already have a Dymo label printer which is _perfect_ for short-term labels like on jars/containers or postal labels. But for longer-term durable labels like on desks, tools and plant pots (that will get wet), we don't have a suitable label maker.

I've done a fair amount of research into this and concluded that the **Brother PT-D600VP Label Maker** is ["_the one that I want_"](https://youtu.be/itRFjzQICJU):
https://www.amazon.co.uk/Brother-PT-D600VP-P-Touch-Labeller-Keyboard/dp/B00R6IG28S
![image](https://user-images.githubusercontent.com/194400/89828703-500bb580-db51-11ea-991b-a737586c9681.png)

Here are a few of the benefits:

+ The machine turns on and prints labels _fast_ 30mm/second.
+ The labels are laminated, durable, weather proof and don't fade. 
+ Print on long-lasting [_Fabric_ Iron-on Tape](https://www.amazon.co.uk/NineLeaf-Compatible-Brother-P-Touch-PT-D210/dp/B088ZPL347) useful for say numbering bed linen/towels in a co-living house
![image](https://user-images.githubusercontent.com/194400/89839255-3ffdd100-db65-11ea-80d7-f04f2dd38f91.png)
+ Wide Range of ribbon/label colors and sizes (widths) from 6mm to 24mm
+ Automatic tape detection means the preview on the screen always corresponds to the width of tape loaded
+ Easily add icons/images in your labels including Barcodes/QR Codes
+ Print from PC/Mac using USB or disconnected from computer with manual input.
+ Create your own templates directly on the printer (up to 99 presets/memory)
+ Label tape is reasonably cheap and there are several generic "compatible" brands with good reviews on Amazon (_i.e. it's not some proprietary system where the consumables are extortionate_)

Yes, there are _cheaper_ machines. But why waste time on something _worse_?

**Comment by iteles** [comment]
What I _hate_ about the Dymo printer we already have is the software. It’s SLOW to work with and limited in functionality as well as word placement options. 

https://smile.amazon.co.uk/dp/B0031SG048/

![1DB7ED53-7F7E-4AFC-ABB5-45D8FFA7BDFA](https://user-images.githubusercontent.com/4185328/89845352-231dc980-db76-11ea-914f-e85a2b8765c0.jpeg)

I’ll look up a demo of usage of this one on YouTube out of curiosity to see if it shares the same problem. 

The versatility of the printing materials is cool.

**Comment by nelsonic** [comment]
Inês, given that the Brother Label Maker does not require connection to a computer and it switches on instantly and has "one-touch" printing, I don't think we are going to have the same issue. 

As for the Dymo, I think we should connect it to a dedicated "Admin" machine and delegate it to an "admin" person.

**Comment by nelsonic** [comment]
@iteles there are quite a few options for ribbon colors including "**pastel**", **gold**, **neon** and, I kid you not, "***rainbow glitter***":
https://www.amazon.co.uk/Aken-Compatible-Replacement-Brother-PT-D400-12mm/dp/B07WFSMJKV 
![image](https://user-images.githubusercontent.com/194400/89846969-99242f80-db7a-11ea-90d9-1b6ae3d24eeb.png)

Do you want to get a specific color for organising a specific type of thing e.g. stationery? 
We can always order the tape cartridges later. No need to get them now. Just in case you want them sooner ... 👍

https://www.ebay.co.uk/itm/TZe-231-Laminated-Label-Tape-Printer-Compatible-Brother-P-Touch/123902779131
![image](https://user-images.githubusercontent.com/194400/89847185-33847300-db7b-11ea-9694-e859eaf70df4.png)


An immediate application is to label the AirCon Remotes so we know where each one belongs. 💡 
Also re-labelling the breakers in the consumer unit (electrical box) so the Bathroom Extractor fans aren't labeled as "Lights"! 🙄

**Comment by iteles** [comment]
I have a preference for solid colours (not `MPHA31` for example) and no neon colours (like `AZe-735`) but other than that, I would only specifically request:
![image](https://user-images.githubusercontent.com/4185328/89886719-02c92b80-dbc5-11ea-9216-da9a21999855.png)
![image](https://user-images.githubusercontent.com/4185328/89886781-1a081900-dbc5-11ea-836f-e3eb39fa53fe.png)
![image](https://user-images.githubusercontent.com/4185328/89886832-2d1ae900-dbc5-11ea-923a-4a60d9210b4c.png)
![image](https://user-images.githubusercontent.com/4185328/89886907-50459880-dbc5-11ea-97fb-c9f68f14fe57.png)

**Comment by nelsonic** [comment]
@iteles yeah, totally agree that **solid colors** is the way to go. 👍 
I don't _understand_ how anyone could think that having a _busy_ background on a label is a _good_ idea.
I think we've got all the **`main`** solid/primary colors covered in the pack of label cartridges I've got in the Amazon cart. I'm getting both 12mm and 24mm labels because, as noted above I want to print QR/Barcodes on several items (_power tool hard cases and their corresponding shelf spaces_) and I want the labels to be visible from a decent distance, like 2m away. 

Planning using **Orange** `#FFA500` for all the labels in the ([D&T](https://en.wikipedia.org/wiki/Design_and_Technology)) "Lab". 
https://www.ebay.co.uk/itm/Replace-Brother-TZ-231-TZe-Label-Tape-Printer-P-Touch-Laminated-24mm-18mm-12mm/124212008842?var=425063566013 
![image](https://user-images.githubusercontent.com/194400/89912210-310d3200-dbea-11ea-8279-54fecacd6ed3.png)



If you don't have any specific needs, I will go ahead and place the order.

**Comment by iteles** [comment]
Yep, please go ahead and place the order 👍🏻

**Comment by nelsonic** [comment]
£25 of VAT ... worth sending to Champs for forwarding or send directly to PT?

**Comment by iteles** [comment]
Worth sending to the Champions if it can be taken out of the box.

**Comment by nelsonic** [comment]
@iteles it comes in a hard case that I'm keen to hold onto: https://www.brother-usa.com/products/ptd600vp
![image](https://user-images.githubusercontent.com/194400/89956235-ab5ea600-dc2c-11ea-8155-b13db4966c7b.png)
It's kinda bulky ... But considering the postage to PT is £9 and the VAT is £25 i.e. **`£34`**
![image](https://user-images.githubusercontent.com/194400/89956340-e3fe7f80-dc2c-11ea-9f74-cc5603faf58c.png)
it could be worth it for CC reroute the whole AMZN box as-is given that they are already sending us other things ... 💭

**Comment by iteles** [comment]
Plugging in the specs from Amazon (plus a bit for packaging) to parcelmonkey:
![image](https://user-images.githubusercontent.com/4185328/89994961-bc390700-dc80-11ea-8077-f13b22513717.png)

Seems worth it 👍 
![image](https://user-images.githubusercontent.com/4185328/89994904-a9263700-dc80-11ea-8142-2b02b586a2e5.png)

**Comment by nelsonic** [comment]
OK. cool. Will check with CC if they are going to be there to receive ... 💬 
Just checked. CC only back on 24th Aug ... 💭  So no point sending anything to them ... ⏳ 
But label maker defo **not** "**urgent**" so I'm going to put it in the "save for later" till then. 👍

**Comment by iteles** [comment]
Order placed 🎉 
![image](https://user-images.githubusercontent.com/4185328/90988032-77b64100-e587-11ea-8567-24b9f49feee3.png)

**Comment by nelsonic** [comment]
The labels arrived last week and appear to be correct. @iteles assigning this back to you for confirmation/sign-off.

**Comment by iteles** [comment]
Yep, they arrived on Friday and are the right ones. Thanks for ordering!
