### ISSUE TITLE
Install Pull-up Bar

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#142]
Thinking of installing the Decathlon Pull-up Bar on the wall in basement on the wall above the back door:
![03DD2BAB-6020-4903-8C74-D61D9A21C167](https://user-images.githubusercontent.com/194400/92301160-2891e800-ef59-11ea-82bb-7a5cf6cd7ef9.jpeg)

The idea is to have it somewhere I walk past every day so that I don’t have any excuse not to *use* it. 

# Todo

+ [x] measure, check for cables/pipes/wires, drill & mount

@iteles any objection? (Or better suggestion for location)?

**Comment by nelsonic** [comment]
Annoyingly, after measuring for the height of the bar (fixings) I checked for joists and there is a supporting beam running through the it:
![A169E390-512F-4D6D-AAC3-BD53AA5EE9E1](https://user-images.githubusercontent.com/194400/92303444-c93dd300-ef6c-11ea-9778-2d953e4e80e1.jpeg)

So I’m scouting a new location on the *outside* of the building... 🔍

**Comment by iteles** [comment]
I was just about to suggest _outside_ the building may be better. 
Although we have ventilation, I have a preference for  sweaty exercise to take place either _outside_ or in a designated area, rather than in a corridor.

In that exact location, you also have the issue of it being right across from the lockers and it would be awkward for people trying to get to the lockers or outside when someone is grunting with effort behind them.

How about _just_ outside, on the wall to the left of the basement door, on the way to the pool?
It would be a good location for people coming to or from the pool to stop for a little arm 'warm up' 😆

**Comment by nelsonic** [comment]
@iteles **_how many_ pull-ups** do you think it takes to get "_sweaty_"? 
And how many people do you know who can do that many? 🤷‍♂️ 
Also, how _long_ do you think it takes to do **10 reps**? 
_Most_ people are not doing more than 10 in one go.
So the chances of anyone having to _wait_ are minimal. 

As for the outside location, I have already tested immediately outside the basement door and the concrete is all rebar reinforced so it makes it difficult to drill into. 🙄  ... but I'm thinking at the top of the first flight of stairs. 💭

**Comment by iteles** [comment]
I was making the assumption that people would use the pull-up bar both before and _after_ workouts when they're already sweaty.

Shame about the concrete being rebar reinforced there (for drilling purposes, nice from a structural perspective 😄 ).

**Comment by nelsonic** [comment]
Today I did a bit of backyard tidying in prep for installing the pull-up bar. still about 5h of work to do for the back yard, which I think deserves a _separate_ issue. But I think I can get the pull-up bar area cleared with 1h of tidying ... 💭

**Comment by nelsonic** [comment]
In case you're wondering why there hasn't been as much progress with this issue (_as I would like_), 🙄 
it's blocked by the fact that our drill is loaned to someone ... ⏳ 
As soon as we have it again, the pull-up bar will be installed on the wall. 👍

**Comment by nelsonic** [comment]
![922DD39A-2018-4691-88D0-80F7543CC67C](https://user-images.githubusercontent.com/194400/94990970-d05dfe00-0577-11eb-8947-104aad91941f.jpeg)
