### ISSUE TITLE
How to Record Security Video?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#169]
## Context 

We plan to use Networked (PoE) Security Cameras to help secure the _outside_ of the house: https://github.com/dwyl/home/issues/130 
Having the Cameras is a good _start_, but there's not much point having them if we don't _record_ the data. 💭 
(_from a security perspective, if someone tries to break into the house at 4am 
and we don't record it somewhere, there's kinda no point in having the cameras ..._)

We already have Ubiquiti/Unifi Networking equipment (the PoE switch and Access Points) https://github.com/dwyl/home/issues/133
While I would definitely prefer to have a fully Open Source solution, I feel that 

## Two Options

If we stick with the Ubiquiti Networks Ecosystem (_which I think is wise given their focus on security_),
there are two options we can chose from:

## 1. Cloud Key G2 Plus with a built-in **3Tb** Hard Drive

The Cloud Key G2 Plus is a multi-purpose device that does both network security and video recording.
It can be configured to _just_ do the Unifi Protect (video monitoring + recording).

The specs say it can control up to **15 UniFi cameras**.
The device has an eight-core 64bit Arm Cortex 53 processor with 3 GB RAM. It consumes **`12.95W`** (PoE).
https://dl.ubnt.com/datasheets/unifi/UniFi_Cloud_Key_G2_Plus_DS.pdf

https://store.ui.com/collections/unifi-protect-nvr/products/unifi-cloudkey-gen2-plus
![image](https://user-images.githubusercontent.com/194400/103160643-b24b1700-47cf-11eb-9bfa-40923010b698.png)

[![image](https://user-images.githubusercontent.com/194400/102902746-47b07900-4467-11eb-829a-42ecefca02de.png)](https://youtu.be/H_a1BCf1jH0)
https://youtu.be/H_a1BCf1jH0

Cheapest available in PT is **€199**
https://www.mbit.pt/informatica/redes/firewall/ubiquiti-unifi-controller-cloud-key-g2-plus
![image](https://user-images.githubusercontent.com/194400/102904806-24d39400-446a-11eb-8884-886a4df9d978.png)

## 2. UniFi Protect Network Video Recorder (UNVR) 

The more expensive option is the UNVR which costs $299 just for the box (without any hard drives).
https://store.ui.com/collections/unifi-protect-nvr/products/unifi-protect-nvr
![image](https://user-images.githubusercontent.com/194400/103151987-10014400-477b-11eb-960c-ab2e7077df7a.png)

Cheapest in PT is €318 https://www.mbit.pt/ubiquiti-networks-inc-nvr-ubiquiti-unifi-protect-network-vid
![image](https://user-images.githubusercontent.com/194400/103152194-79825200-477d-11eb-8f6f-4786901a6565.png)

Watch this overview if you want to understand more: https://youtu.be/NAhCYgbb2aM
[![image](https://user-images.githubusercontent.com/194400/103161166-86329480-47d5-11eb-8da1-1b0d54c19cc4.png)](https://youtu.be/NAhCYgbb2aM)

The reason I'm not going into more detail on this is that I think that it's not the best option for us right now.
To make this device worth while we would need to buy at _least_ two hard drives to use it in RAID 1.
Reviewing the Hard Drive compatibility list:
https://help.ui.com/hc/en-us/articles/360037340954-UniFi-Protect-Hard-drive-compatibility
We would need to get at least Western Digital Red drives around €200 each.
So the total **up-front cost** would be **`€700`**.
And given that it consumes **`100W`** (2.4kW/day) the on-going running costs are _significantly_ higher.
It would need to be on permanently, so 365 x 2.4 = 876kw ~ €87/year

**Comment by iteles** [comment]
More like ~€105/year in energy costs.

But agreed that this may not be the _best_ fit right now 👍 

My instinct is that this **might be overkill** for Braga home in it's current incarnation, given its central location and proximity to police stations (literally round the corner). It's not so much about the cost but the requirements.

The key concern is external security followed by some back-ups internally in areas where people are likely to leave valuables but we also don't want this to be a nanny state. There needs to be some accountability in place and we have tight security in the door system as well.

**Comment by nelsonic** [comment]
@iteles yeah, **~€105/year** in energy costs seems like overkill in the short-term. 

I think I'm going to place an order for the **Cloud Key G2 Plus** and a **G3 FLEX Camera**: https://github.com/dwyl/home/issues/130#issuecomment-751525420

**Comment by nelsonic** [comment]
For future ref, the cheapest way of getting the best hard drives is to buy _external_ drives and "harvest" them:
https://www.pcdiga.com/disco-externo-3-5-western-digital-wd-black-d10-game-drive-8tb-usb-3-2-preto
![image](https://user-images.githubusercontent.com/194400/103181661-8bf2ad80-489b-11eb-80a0-a509a42ffacc.png)

**Comment by nelsonic** [comment]
@iteles the current shopping cart for the basics (Cloud Key + 3 Cameras) is €480
![image](https://user-images.githubusercontent.com/194400/103447645-cb4b4080-4c85-11eb-93e3-9fa7363136e0.png)

**Comment by nelsonic** [comment]
The price of the cameras has gone up on **mbit** since I checked yesterday ...
![image](https://user-images.githubusercontent.com/194400/103562811-9cb2ad00-4eb3-11eb-80d5-56fca5802e10.png)

Marginally cheaper on Senetic ... but postage is €20 💭 
![image](https://user-images.githubusercontent.com/194400/103627351-6289ef80-4f35-11eb-9ea2-76cd347b593e.png)

**Comment by nelsonic** [comment]
+ UCK-G2-Plus: https://www.senetic.pt/product/UCK-G2-PLUS
+ Nano Switch: https://www.senetic.pt/product/N-SW
+ G3 Camera Pack: https://www.senetic.pt/product/UVC-G3-FLEX-3

**Comment by nelsonic** [comment]
https://eu.store.ui.com/collections/unifi-protect/products/unifi-cloudkey-gen2-plus

**Comment by nelsonic** [comment]
Placed the order for the CloudKey Gen2 Plus: https://github.com/dwyl/home/issues/130#issuecomment-1117938928

**Comment by nelsonic** [comment]
Got the cloud key a while back. It’s been working fine. Closing. ✅
