### ISSUE TITLE
Plunge Pool?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#18]
We need to investigate if this is feasible in both cost and space.

E.g: 
http://icoolsport.com/cartpage/viewproduct/977/iCool_Twin

**Comment by iteles** [comment]
@nelsonic Are you still considering this?

For now, I think we have maxed out the space around the pool and this would only make sense next to the sauna.

However, I do think it's more important to have a barbecue area #77 in that spot over the plunge pool given all our other existing amenities!
I suggest we close this for now unless you're super keen.

**Comment by nelsonic** [comment]
@iteles I _agree_ that we don't have the _space_ for anything `else`. 🤷‍♂ 
Closing for _this_ iteration of @home ✅ 
Worth considering for a _future_ location. 💡
