### ISSUE TITLE
Bamboo Storage Boxes

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#182]
Thinking of ordering one of these to test as storage for smaller items:
https://www.ikea.com/pt/en/p/skakare-storage-box-bamboo-20497810/
![image](https://user-images.githubusercontent.com/194400/132138544-8ce38c27-a378-49a9-81d0-327511af8564.png)

**`15cm`** height means they will fit in the entrance shoe rack #181 and can be used to store "useful things when going outside" that we don't want to be visible but still want quick/easy access to.
They are a bit more expensive because they are made from nicer material. 💭 

The narrower version is: https://www.ikea.com/pt/en/p/skakare-storage-box-bamboo-10446680/
![image](https://user-images.githubusercontent.com/194400/132138913-c572dd1e-8659-439b-a083-62d4c9ccd2ae.png)

@iteles can we add 2 of these to the IKEA shopping list? (please/thanks!)

**Comment by iteles** [comment]
Ordered and should arrive 10-Sep-2021

**Comment by nelsonic** [comment]
@iteles thanks for buying these. They arrived and are in-use. 👍
