### ISSUE TITLE
Library Book Shelves Part 2 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#190]
Having recently installed the 9 bookshelves in the library #179 and unpacked a few boxes of books:

![7AFF1DD7-E6AB-4C93-B45A-A473D1589C6F](https://user-images.githubusercontent.com/194400/155232900-9715dec5-46bd-4ec8-8efd-d6c77451230a.jpeg)

 I’ve realised that we have accumulated “too many” books and need more shelf space.

> **Note**: Yes, it may look like we still have a couple of “empty” shelves in this picture. But they are already pre-destined for children’s books which we already have enough of to cover one of the shelves and we expect to acquire plenty more in the next couple of years. We cannot put “non kid” books on these bottom shelves as our 👼 will *investigate* (destroy) them. 

So I’m considering putting another set of shelves on the south wall next to the entrance of the library:

![DE5D942F-18D4-4895-AF62-D5FC7A468A07](https://user-images.githubusercontent.com/194400/155233695-1e99c3fc-f4e0-4b79-80b5-d1299860554d.jpeg)

The wall is **`112cm` wide** so **60%** of the width of the North wall. It would give us a chance to have taller shelves for hardbacks and cook/recipe books which apparently are all too tall for the next week costing shelves, hence the horizontally stacked books …

@iteles thoughts?

Edit: A bit more detail:
1. Given that the width of the wall is only **`112cm` wide** it means the pieces can fit in our micro-car. e.g: https://github.com/dwyl/home/issues/184#issuecomment-938179260 so there are no dependencies on having access to a bigger car or renting a van. 
2. This will give me a chance to test my revised design which will be (a) faster and less frustrating to build and (b) hopefully easier to keep level.
3. The cost will be around **`€65`** (_**one sheet `15mm`** Birch Ply_) of materials and **`T8h`** in time. 

# _Proposed_ Production Plan

+ [x] Measure and re-measure the space at various points on the wall to confirm width and height
+ [x] Sketch out new design and confirm that it will work by doing a mini test in the workshop
+ [x] Design
  + [x] Prepare cutting list
    > Yes, I know the Leroy PlyWood isn't great quality #123 ... but the result on the _existing_ Library shelves https://github.com/dwyl/home/issues/179#issuecomment-1046326147 is more than good enough for storing books and it means we don't have waste time ordering/transporting/managing/cutting full sheets and can get this done _much_ faster.
  ~~+ Print cutting list on Epson EcoTank printer (printed is much easier for the Leroy person than trying to give them a screen to read off ...)~~
+ [x] Buy Materials --> I _found_ enough **`15mm`** Birch Plywood pieces in the workshop to make the shelves so skipped the trip to the hardware/lumber store and just got started with the build phase!
  + [x] _Prepare_ the workshop for the new project!
  ~~Take the cutting list to Leroy~~
  ~~Get ticket for wood cutting service _first_ to avoid waiting~~
  ~~Select the best looking + flattest plywood sheet from their stock~~
  ~~Wait patiently for turn ...~~
  ~~Give cutting list and plywood sheet to Leroy employee and explain importance of the order of cuts (to avoid material wastage!)~~
    > Note: the material width is **`125 cm`** so they will need to do a length cut first. 
    I intend to use this **`4cm`** "off-cut" as part of the design. So this cut needs to be done first. 💭 
  ~~Gather cut pieces and place on trolley and take to checkout for payment.~~
  ~~Load cut materials into car & drive home.~~
  ~~Unload materials & prepare for processing!~~
+ [x] Build! 
  + [x] Cut the 8 shelves to size
  + [x] Cut the strips that will be screwed to the walls
  + [x] Route a **`15mm`** groove through the centre of the wall-mounting strips for slotting the triangular support
  + [x] Cut and sand 16 support brackets --> made these from offcuts. 🙌 
  + [x] Measure the positions of the brackets on the strips
  + [x] Drill & countersink holes just above shelf position in the strips for wall mounting.
  + [x] Glue and brad-nail the triangular supports in place and leave to cure overnight. 
+ [x] Installation
  + [x] Mount the vertical strips to the wall
+ [x] Finishing
  + [x] Round the edges of the bottom 6 shelves so people walking in/out of the library don't encounter sharp corners
    see: https://github.com/dwyl/home/issues/190#issuecomment-1049339523
  + [x] Cut concentric circle hole in 4 of the shelves to hold pot plants, see: https://github.com/dwyl/home/issues/190#issuecomment-1052677225
+ [x] Measure locations for installation cut-outs on shelves in-situ to ensure they fit.
  + [x] Cut the fitting grooves with jigsaw
  + [x] Drill mounting holes 2 per shelf for holding the shelf in place (in addition to the glue)
+ [x] Mount & glue the shelves in place

**Comment by iteles** [comment]
Yes, 100%.

We also need a space higher up in the current shelves for kids books that will get destroyed by little hands who can reach the first two shelves too (thin pages, etc for older kids).

We should have a think about the bottom shelves here. They might be a better spot for a couple of baskets of things that can't get destroyed or closed boxes.

**Comment by nelsonic** [comment]
@iteles ia there anything else @home related that you feel is a higher priority or should I focus on this so we can get the Library done and dusted? Design phase will be around T1h.

**Comment by nelsonic** [comment]
@iteles Glad you're on-board with this extension. 🙌 
Glad you agree that _finishing_ the library is a priority and will make a big diff. 📚
We're skipping the _first_ step in the [KonMari Method](https://konmari.com/about-the-konmari-method/) ...
But tidying the books and having the _entrance_ of the house free of boxes will be good. 

With the knowledge we have gained from building the first set of shelves, 
we can make a far more informed choice about the dimensions & design for the next set. 
I was thinking of making them all **30cm deep** and **32cm** tall so that _all_ the Cook books and coffee-table size books will fit. But on the off-chance that we have _even_ taller books, 
do you think we should have a 33 or 34cm tall shelf? and if so how high up should it be? 
e.g. if we made the **5<sup>th</sup> Shelf `34cm` tall**.

As I wrote above, I think I could prep the _Design_ for this pretty quick. 🧑‍💻  (e.g. **`T1h` _tonight_** after 👼 goes to bed...)

**Comment by nelsonic** [comment]
The height is **`2670mm`** (rounded down) minus **`100mm`** for Roomba clearance which gives us: **`2570mm`**.
2570 / 320 = 8.03 i.e. _exactly_ **8 shelves**. 

Going to make the eye-height shelf **`280mm`** high so that the she shelf below that can be **`340mm`**.
**`280mm`** is more than enough height for the _vast_ majority of books. 


_Was_ thinking of getting a single sheet of 8 x 4 (2500 x 1220) **`15mm`** Birch Plywood:
https://www.leroymerlin.pt/Produtos/Madeiras-acrilicos/Paineis-construcao/Paineis-contraplacado/WPR_REF_18896675
![image](https://user-images.githubusercontent.com/194400/155378407-b20413e3-f3de-48da-ba9a-e4807650121e.png)

However ... _found_ 5 sheets of **`1200 x 600 x 15mm`** Birch Ply in the wood rack which is _perfect_ for this project. 🙌 
Going to crack on with cutting it down to size this evening. 🤞 
But sadly I don't have **`T8h`** to _finish_ this today. ⏳

**Comment by nelsonic** [comment]
I’ve made decent progress this evening. More than half way there. It helps that the design is considerably simpler and has built-in “error-correction”. 🙌
I will be pretty much ready to *install* the shelves tomorrow if I get time during the day. Otherwise only next week. 🤞

@iteles **quick question**: should I round the corner of the shelf that will be near the entrance/doorway to mitigate people walking into it and hurting themselves? 💭
It adds a about hour to the project as there is also sanding and round-over routing required, but it will mean that people walking past are less likely to hurt themselves… LMK your thoughts? 🙏

**Comment by iteles** [comment]
I think this would make it look amazing! If you don't mind the extra hour, I think it would also be piece of mind for parents of kids rounding that corner at speed. We don't want A to take an eye out!

**Comment by nelsonic** [comment]
Ok, cool. I will add an extra 6 cuts to round all the shelves below 2m such that there are no sharp edges for anyone to hurt themselves on. 👍🏻

@iteles do you have any preference for the *radius* of the corner? 🪚

**Comment by nelsonic** [comment]
Made circular holes in 4 of the shelves for pot plants: 🪴 

<img width="686" alt="image" src="https://user-images.githubusercontent.com/194400/155860401-7a18bfb2-c22d-4077-bb10-8a2bd4425bcf.png">

This photo isn't great. But you get the idea. 💭

**Comment by nelsonic** [comment]
_Really_ looking forward to having _all_ our books unpacked and stored on the shelves. 🙌 
Think we can get this **`done`** on tomorrow evening with **`T2h`** of cleaning and unpacking. ⏳

**Comment by iteles** [comment]
Super excited about this. They look amazing with the plants! 😍 

Can you please leave the rest of the books to me? We'll get the room properly cleaned today and then tomorrow I can focus on this (I estimate 3 hours but I haven't done it in a while!) :tada:

**Comment by nelsonic** [comment]
@iteles glad you're excited about having an organised library. 🎉 
Happy to leave the remaining boxes for you to unpack. 👍 
I'm equally keen to get a decision on what we're doing with the excess boxes: #191 📦

**Comment by nelsonic** [comment]
https://twitter.com/bcredibility

**Comment by nelsonic** [comment]
@Stephanymtr want to take & upload a photo of the south wall bookshelf in it's current state? 🙏 📚

**Comment by Stephanymtr** [comment]
South wall bookshelf + plants. I just watered them. They are happy again. ![20220316_152515.jpg](https://user-images.githubusercontent.com/91985721/158626826-87d8f8e1-7223-469c-a559-0da6c4e8eb64.jpg)![20220316_151703.jpg](https://user-images.githubusercontent.com/91985721/158626852-0ffc2363-13f0-4f94-a9c1-13220a02b8d3.jpg)![20220316_151655.jpg](https://user-images.githubusercontent.com/91985721/158626872-ddd177d5-9136-4054-90cb-a9e51f6df3cb.jpg)![20220316_151712.jpg](https://user-images.githubusercontent.com/91985721/158626887-96d97cf3-4a8e-4758-8675-b04d72bef3d4.jpg)

**Comment by nelsonic** [comment]
On the morning of March 24th I woke to a loud crashing noise. 
The _heavy_ ("_coffee table_") books on the **5th Shelf** were too much for the "minimalist" shelf brackets 
and they had caused a material failure in the shelf taking out shelves 4 and 3 on the way down:

![image](https://user-images.githubusercontent.com/194400/162065570-18a2e75d-bfeb-4dd4-92cd-8414d5ed7284.png)

It was a mess but thankfully:
a) nobody was around for any books (_or pot plants_) to fall on 😥 
b) none of the pot plants broke and no books were damaged.

It was a good lesson in material strength/weakness and a good reminder to _over engineer_ things instead of making them "minimalist" ... 🙄 I take full _responsibility_ even though on close inspection, the material failed where I'm _sure_ a better quality of plywood #123 would not have had the same issue. 

![image](https://user-images.githubusercontent.com/194400/162065427-d2a1ddab-629d-4dd5-ab96-06a197815e05.png)

As you can see from this photo the shelves ripped the plywood apart (delaminated it):

![image](https://user-images.githubusercontent.com/194400/162066785-dbc83fb7-793b-40c6-a241-ebc95695b632.png)

The actual strip of plywood split:

![image](https://user-images.githubusercontent.com/194400/162066903-1520056f-e05c-407c-b835-ddde92fa0dda.png)

I did a full analysis of the material at the time and concluded that it would not have happened if I had used screws.
The glue was fine, but it only adhered to the surface of the ply so the actual bonding of the ply was the weakest point.
With screws it would have been a lot stronger.

Didn't want to post the photos of the "failure" until I had _fixed_ the issue. ⏳ 

I re-made the strips that failed and this time I added screws from the wall side so they are extra strong. 
But I didn't stop there. I made _super_ over-engineered wall brackets #196 which are attached to the wall with 4 plugs+screws rated for  **`50kg`** each. The wall brackets are what are providing most of the strength to the newly re-installed shelves: 

![DA931C6E-F385-40C1-80AA-3BAC767D8E0F](https://user-images.githubusercontent.com/194400/161802751-125dbaa7-2f5b-4039-b6db-abd2811ce56b.jpeg)

See: #196 

@iteles back to you to stack the books the way you want them. 📚

**Comment by nelsonic** [comment]
Closing as this portion of the project is complete. ✅ 
We still have to _organise_ the books on the shelves ...📚 
But we have a `new` task for that: #216 ⏳
