### ISSUE TITLE
What to do with empty boxes? 📦 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#191]
Having recently unpacked a few boxes of books as part of Library #179 & #190, 📚 
we now have a stack of empty boxes in the corridor: 📦  🙈 

![image](https://user-images.githubusercontent.com/194400/156377067-efbd9684-16a6-43f9-abd7-3ab560fe5e3e.png)

They are an eye-sore and we need to remove them.
These boxes are high quality "cartons" made of 4 layers of card and have a lot of clear tape on them which makes them _very_ strong. Feels like a waste to just _recycle_ them. But we don't have a _need_ for them at this moment. 

# Question

@iteles Do we want to _keep_ any of the boxes? e.g. use them for storage in the attic or flatten them for a future move?
***or*** should we just recycle them all ASAP?
Thanks!

**Comment by iteles** [comment]
It would be a total waste to recycle them. I would suggest that in the immediate term we store them in the attic, in the impossible to reach section at the very edge of the roof.

**Comment by nelsonic** [comment]
Seems like something we could get done in **`T10m`** a box in each hand x 6 trips each up the stairs. 💭

**Comment by iteles** [comment]
If we do a little human chain up the stairs it'll be even quicker 👍

**Comment by nelsonic** [comment]
I've taken 2 up to test the idea.

**Comment by nelsonic** [comment]
Human chain is a good idea. The "hard" part is the attic. Still think we can get it done in **`T10m`** ...

**Comment by Stephanymtr** [comment]
I can help as well. Are we taking them apart or taking them upstairs as they are?

**Comment by nelsonic** [comment]
I think we are just storing them as they are because part of the structure is the insane amount of packaging tape on them.
Happy to dismantle if @iteles prefers. 💭

**Comment by nelsonic** [comment]
Moved all the empties to the rafters as you suggested.

**Comment by nelsonic** [comment]
Once you have emptied the remaining cartons of books (for #190) that are currently on the library floor, if you leave the empty boxes in the corridor (and tell me) I will move them to the attic and we can we be done with boxes in the middle floor once and for all. 🤞

**Comment by iteles** [comment]
@nelsonic I believe this is done?

**Comment by nelsonic** [comment]
Mostly. A few still on the windowsill ... would be good to remove _all_ of them. But yes, the main ("cartons") are gone.
