### ISSUE TITLE
Support Brackets for Library Bookshelves

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#196]
Sadly, the Construction Grade Plywood I used to make the South Wall Library Bookshelves https://github.com/dwyl/home/issues/190 was not very strong ... 😢 

Long story short, I need to make 4 trusses for the shelves that have most weight on them.
I will make them out of "found" materials in the workshop and I expect it to take me around `T2h`.

# Todo

+ [x] Measure the space.
+ [x] Measure the available "found" materials (off cuts from previous projects)
+ [x] Confirm we have enough material for at least 4 trusses
+ [x]  Cut and construct the first truss as a trial
+ [x] Test mount it!
+ [x] Make 3 more trusses and mount them.

**Comment by iteles** [comment]
They look _really_ good and there's no way it'll buckle under the heavy weight of all our recipe books 😉 

I have nothing constructive to share as it looks great and I agree with you on the bottom shelf.
Happy to help repopulate :+1: 🚀

**Comment by nelsonic** [comment]
@iteles cool. Thanks for the feedback. Closing this issue in favour of #190 assigned to you for stacking. 📚  🤞
