### ISSUE TITLE
Kitchen backsplash

### ISSUE THREAD

**Issue by iteles** [dwyl/home#197]
We of course need a backsplash across multiple surfaces of our kitchen, behind all 3 of the food prep/cooking areas.

It needs to be:
+ Durable
+ Easy to clean
+ Easy to maintain
+ Look good in videos filmed in the kitchen yet also be unobtrusive so as not to pull attention away from the main focus - people and food (a la Pick Up Limes):
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/4185328/162977100-3b5e1d46-bbb6-4942-96b8-c18d9cf1015d.png">

**Comment by nelsonic** [comment]
Totally agree with all the requirements and Pick Up Limes as a good example. 👌 
The grey behind **Sadia**, plants, fruit & flowers are all _very_ strategic for framing the shot. 📷 
I honestly would be happy with doing the _exact_ same as it looks great.

**Comment by nelsonic** [comment]
@iteles can we move forward with this now that the counters have been installed? 🙏

**Comment by iteles** [comment]
Furthest thing from my mind right now. Thanks for the chase.

I just tried now and we agreed he would call us tomorrow as soon as his morning job was done (which is likely to run into the afternoon) and agree a time to come tomorrow afternoon (I gave him free rein of our day to make sure this gets done).

**Comment by nelsonic** [comment]
The advantage of having external contractors to do the work is that you don't have to spend _too_ much time thinking about it to make progress on it. A 1 minute phone call or text to follow-up ***or*** I can do it if you don't have time. 👌 

Thanks for confirming that he will call us tomorrow. 👍

**Comment by nelsonic** [comment]
This afternoon **`Vitor`** visited the kitchen and we discussed the best options for kitchen backsplash. 
Then after work we visited **`Jolemos`**: https://www.jolemos.net/fabricas-de-ceramicas

And made our selection of ceramics for the kitchen backsplash ...
![image](https://user-images.githubusercontent.com/194400/195424361-3eafb2d5-688e-47e3-a2f4-90f4a8bdd586.png)

@iteles has sent **`Vitor`** a message requesting is availability for installation. 🤞

**Comment by iteles** [comment]
Super flattering photo, thanks 😆 

We have the quote. This seems very steep to me given that this is maaaaaaaybe a day's work and the materials (cement and grouting) are really cheap 🙄 
I think this guy took one look at the kitchen and thought 'yep'.

<img width="680" alt="image" src="https://user-images.githubusercontent.com/4185328/195576084-593b9991-208f-4ac6-88d5-68c237472953.png">

![9AA4DA21-086C-4C46-89B0-C34E34DE1113](https://user-images.githubusercontent.com/4185328/195576289-1d6f5f82-2efd-43e9-afb3-cd821e0e7b93.jpg)

Ceramics: 7 x €17 = €119 (a little extra as they come in packs of 2 and we'll need a spare)
Calha: €10
Installation: €320 

_Sub-Total: €449_

**Total including VAT: €552**

**Comment by nelsonic** [comment]
Yeah, this is _definitely_ overpriced. 🙄 
What do you want to do? Shop for alternative quotes? 🤔 
Or just get this done ASAP? ⌛

**Comment by iteles** [comment]
Super flattering photo, thanks 😆 Note that this is not a photo of our selection. This is a photo of me explaining why 'absolutely not this one'.

We have the quote. This seems very steep to me given that this is maaaaaaaybe a day's work and the materials (cement and grouting) are really cheap 🙄 
I think this guy took one look at the kitchen and thought 'yep'.

<img width="997" alt="Screenshot 2022-10-13 at 14 11 04" src="https://user-images.githubusercontent.com/4185328/195605923-aa8d0d7d-19b5-42df-a7ed-145e1d589f42.png">


![9AA4DA21-086C-4C46-89B0-C34E34DE1113](https://user-images.githubusercontent.com/4185328/195576289-1d6f5f82-2efd-43e9-afb3-cd821e0e7b93.jpg)

Ceramics: 7 x €17 = €119 (a little extra as they come in packs of 2 and we'll need a spare)
Calha: €10
Installation: €320 

_Sub-Total: €449_

**Total including VAT: €552**

**Comment by nelsonic** [comment]
Yeah, this is _definitely_ overpriced. 🙄 
What do you want to do? Shop for alternative quotes? 🤔 
Or just get this done ASAP? ⌛

**Comment by iteles** [comment]
Have texted Eng. Luís Filipe Teles to ask if he knows anyone.
If we can mobilise an alternative quickly, so be it. If not, then this 👍

**Comment by nelsonic** [comment]
FYI: I don' think this is a one-day job at all. If **`Vitor`** does, that's great, maybe he's _that_ good. 🙌 
It's one day of preparing the walls one day of installation and another of tidy-up at _least_. 💭 
Yes, **`€320`** is a _lot_ by PT standards in the context of a multi-unit developer. 💰 
But in terms of a one-off custom job like this ... you might find it **`€100`** cheaper. 🤷‍♂️ 
But it's barely worth your time/effort in terms of "search costs". 🔍 ⌛ 💸 
I would probably sooner pay the **`€100`** "_premium_" to ensure the job is well-done 🤩 
than find someone _cheaper_ who may do an inferior job ... 💭

**Comment by iteles** [comment]
The contacts they had were people who  are already known to us and a little flakey on timelines.

Seeing as we want to get this done, I got in touch with Vitor and confirmed we were moving ahead. He will get back to me with a date tonight or tomorrow.

**Comment by nelsonic** [comment]
Fair enough. Let's get cracking then! 👌

**Comment by iteles** [comment]
Just spoke to Sr. Vitor who is having a minor op tomorrow (pulled forward from the 2nd Nov) but will be out of commission until the end of the week and wanted to come and supervise the men who will be doing the work.

We have agreed Tuesday 25th October provisionally and will keep talking.

We should go and get the material tomorrow or soon 👍

**Comment by nelsonic** [comment]
@iteles know this isn't your "main focus" right now ... 👶 
But has Sr. Vitor said anything recently about when they can come and do the work? 🤞

**Comment by iteles** [comment]
Spoke to Vitor who can go and pick up the tiles from the shop.
I will liaise with the shop and organise for payment and pickup once I have more info from him.

He will call me to give me an updated slot for the work hopefully before the end of the day.

**Comment by nelsonic** [comment]
@iteles you spoke to Vitor last week [I overheard the conversation as we were in the car together...] 🤙 
You agreed to call him back this week to book a slot for getting the work done. 📆 
Was there any follow-up/progress? 🤞

**Comment by iteles** [comment]
Booked in for 3rd January 2023.

Need to call Jolemos and order + pay for tiles. 
@nelsonic We need 5.3m2 of tiles according to Sr. Vitor. Should I order 6 or 7m2 to have some spare?

**Comment by nelsonic** [comment]
@iteles 100% 7m<sup>2</sup> for sure. Wanna get that ordered and _collected_ tomorrow? 💭

**Comment by iteles** [comment]
Ordered and paid for 👌🏻

I organised with Vitor that they would collect it directly from the shop 💁🏻‍♀️

**Comment by nelsonic** [comment]
Paid for with PT Co. Card/Transfer? 🤷‍♂️

**Comment by iteles** [comment]
Transfer.

Spoke to Vitor again today and he agreed that if I call him on Thursday (9-Feb), I can get a definitive date from him for this to actually get done.

Apparently the good weather means all of his half-finished previous work has suddenly become urgent for the owners and the timing is just poor.

**Comment by nelsonic** [comment]
Let's see ... ⏳ 🤞

**Comment by nelsonic** [comment]
https://github.com/dwyl/home/issues/197#issuecomment-1276599807 feels like a _very_ long time ago now ... ⏳ 

thanks for following-up. 👍

**Comment by nelsonic** [comment]
@iteles any luck getting hold of Vitor this week?

**Comment by nelsonic** [comment]
@iteles you sent me a calendar invite for next Monday (8<sup>th</sup> May): 🗓️ 

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/194400/235639592-cd4a52ba-4d43-464e-a3bc-30ca31aca2a2.png">

But didn't post any update on this issue so it's difficult for me to keep track of where we are with this. 💬 
Did Vitor ***`commit`*** to being here on that day to get the work done? 🤞 
Do we need to order the tiles or does he have that under control? 🛒 
Will he expect payment on the day (i.e. do we need to extract the cash from Bank) or can you pay by Transfer/MBWay? 💰

**Comment by nelsonic** [comment]
Cool. Offer to pay for the materials up-front to further secure his commitment to getting the work done. 💭

**Comment by iteles** [comment]
Sr Vitor wrote this down wrong 🤦‍♀️ He SAYS he wrote down 18th instead of 8th.

Either way he has now committed to Monday 15th May.

**Comment by nelsonic** [comment]
Thanks for following up. _Really_ looking forward to having this finished. 🤞

**Comment by iteles** [comment]
Called Vitor earlier today and he confirmed we are on for Monday, at 08h30.

**Comment by nelsonic** [comment]
Rui (Vitor’s) tile guy did a decent job of the backsplash tiles:

![IMG_6584](https://github.com/dwyl/home/assets/194400/76d0a0e5-033d-4738-ba5b-7c03b9793dbd)
![IMG_6585](https://github.com/dwyl/home/assets/194400/92c6124d-5973-457d-bc2f-d51a23b4d812)
![IMG_6454](https://github.com/dwyl/home/assets/194400/08588aa2-523f-4aed-8299-12e7ec20a1ca)
![IMG_6400](https://github.com/dwyl/home/assets/194400/e35e2e16-a81a-42d1-8762-9b3347916b08)

**Comment by nelsonic** [comment]
What is unfinished is: the side panels on all the cabinets still require cuts to be re-mounted:

![IMG_6586](https://github.com/dwyl/home/assets/194400/323719c4-85a6-4b11-a1be-87c4f7f792c4)
![IMG_6587](https://github.com/dwyl/home/assets/194400/04682d12-dccb-4e5a-9419-a99eeca14ef3)

Rui said Vitor would send his carpenter to do the finishing/mounting of the cabinet sides. 

@iteles please follow-up with Vitor when you can to arrange. 🙏

**Comment by nelsonic** [comment]
We definitely paid them in Dec.
There were some defective tiles,
Which Vitor cheekily took away with him…
They may be trying to charge us for the replacements. 💭

**Comment by iteles** [comment]
They're not, the invoice is for the original amount.

I will check this now.

Meanwhile, Vitor has confirmed he will try to get his carpenter out to finish the job this week.

**Comment by iteles** [comment]
This is finished though the carpenter did a shoddy job and still hasn't put silicone where he said he would. 

He's not a great workman so I'm tempted to NOT insist he comes back to do it 😕

**Comment by iteles** [comment]
In the meantime I've confirmed we have in fact _not_ paid Jolemos for the tiles, I'm not sure what I was thinking in my comment above.

[FATURA_B1_1455.pdf](https://github.com/dwyl/home/files/11834641/FATURA_B1_1455.pdf)

@nelsonic Please pay **€123,91** to IBAN: PT50003602949910001182317 asap.

Haven't heard back from Vitor yet and in no real rush to pay him so I'm not chasing.

**Comment by nelsonic** [comment]
@iteles do we have a Company invoice (fatura com NIF d’empresa) for this?

**Comment by iteles** [comment]
We do. I didn't see it here because of the address for now. 
Please pay from company funds 👌🏻

**Comment by nelsonic** [comment]
Paid: 💸 ✅ 
<img width="888" alt="image" src="https://github.com/dwyl/home/assets/194400/6aeebbe9-a780-436b-b0cb-10ab00baaeae">

Proof uploaded to Google Drive. 📁

**Comment by iteles** [comment]
He wants to charge us €80 for the shitty job done by the carpenter:
<img width="1118" alt="image" src="https://github.com/dwyl/home/assets/4185328/72851184-4e66-4fff-9da6-648c47df7c7e">

I should have learnt by now that everyone is a chancer.

I'm not going to throw a fit over €80 but I will make my disdain for the situation well known to him as it would have been a lot better for us to just get this done ourselves.

We won't be using him again anyway because although the job was decently done (aside from the wood panels), it took 7 months of constant chasing to get it done.

**Comment by iteles** [comment]
Boa tarde Vitor

Têm sido dias complicados para a nossa família, pelo que peço desculpa pelo atraso.

Confesso que fiquei surpreendida de ver um custo adicional para o carpinteiro, particularmente porque para além de pensar que fazia parte do trabalho (e só foi necessário por causa da maneira que a tijoleira foi posta - e concordamos que tenha sido da melhor maneira), o trabalho também foi feito um bocado 'às três pancadas' como se pode ver nas fotografias abaixo.
![IMG_5960](https://github.com/dwyl/home/assets/4185328/799a9f29-3cb9-4845-bd93-ddeccfed83ef)

![IMG_5959](https://github.com/dwyl/home/assets/4185328/9fe1b75c-2722-4ba1-8a47-d0e47989d2d7)
![IMG_5961](https://github.com/dwyl/home/assets/4185328/59f7a829-dc05-4f6e-9d6a-72f2f8b10fba)

Não podia deixar de lhe mostrar estas fotografias já que é uma pessoa que marca como a sua empresa é vista.
A parte da tijoleira ficou muito bem, obrigada.

Junto abaixo os detalhes e conforme combinado, peço que nos passe a fatura com **auto-liquidação de IVA:**
SHOSHIN Unipessoal Lda.
NIF: 516002350
Av 31 de Janeiro, 206
4715-052 Braga

Obrigada e mais uma vez peço desculpa pela demora,
Inês

**Comment by nelsonic** [comment]
Send. 👌

**Comment by iteles** [comment]
IBAN: PT50 0033 0000 4565 0312 2730 5

Fatura N.o FT VLS2023/51

€400. 

5 days after I'd already sent him the invoicing details he sent me a very ratty text asking me to pay the sum owed. Like we didn't wait 7 months with me continuously having to chase him to get the work done. 

I told him we couldn't pay without an invoice, as is obvious. We just got this invoice 👍

**Comment by nelsonic** [comment]
Paid and uploaded PDF to Google Drive. 📁

**Comment by nelsonic** [comment]
Unpinning as closed. ✅
