### ISSUE TITLE
Doorbell

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#201]
We need a doorbell. 🔔 

I propose getting a Doorbell G4 **`SKU:  UVC-G4-Doorbell-EU`**
https://eu.store.ui.com/collections/unifi-protect-cameras/products/uvc-g4-doorbell

![image](https://user-images.githubusercontent.com/194400/166717347-a49b9378-f36d-40a3-9336-2af7a4690836.png)

It's **_definitely_ not cheap** and requires additional hardware to function: https://github.com/dwyl/home/issues/130#issuecomment-1117495755
but is feature-packed, has **night vision**, sends a **notification** to your **phone**
allows you to speak to people at the front gate via the App on your phone,
stores data _locally_ (_not in the cloud and has no subscription fees, etc._)
i.e. you can answer your front door from anywhere in the world.

UniFi Protect G4 Doorbell Review: https://youtu.be/q-iQAEPSKYc
[![image](https://user-images.githubusercontent.com/194400/166717818-b7fc77c2-a913-4405-b52c-2a9b534a8689.png)](https://youtu.be/q-iQAEPSKYc)

Linus set his up in a matter of minutes and it looks good; super **wide-angle**!
[![image](https://user-images.githubusercontent.com/194400/166723378-9fd19f9d-f31b-4878-94d1-8bc75fbe16ed.png)](https://youtu.be/o1cgvG1Yadg)

There is also a **Wireless chime** that can be plugged into a standard wall outlet and used with UniFi Protect doorbells:
https://eu.store.ui.com/collections/early-access/products/smart-chime-ea
![image](https://user-images.githubusercontent.com/194400/166723794-370ee84e-d5b4-4020-90d8-b4c89ee0fa0c.png)

But it's out-of-stock (_I've requested a notification_) and we don't need it if we enable notifications on our phones which I actually prefer in terms of **noise** (👶  😴 ) in the short-term. 

@iteles LMK your thoughts on this. 🙏 
We could order it today, get it delivered early next week and have it installed by the end of next week 
(pending availability of Electricians ... but I can do most of the prelim work like drilling holes etc.)

**Comment by nelsonic** [comment]
Order placed as part of: https://github.com/dwyl/home/issues/130#issuecomment-1117938928

**Comment by iteles** [comment]
This seems... expensive. But good quality.
It doesn't seem very vandal-proof though... maybe a little delicate?

My greater concern at this point will be how to fix this to the outer wall in such a way that it won't get stolen because we _know_ people will try to steal it 😬

**Comment by nelsonic** [comment]
@iteles i thought if that. I’m going to embed it in the granite and then apply silicone to glue it in place.

agree that it *feels* exp. Thankfully most passers by won’t know what it is.

**Comment by nelsonic** [comment]
The Ubiquiti doorbell arrived 2 days after we ordered it. 🚀 

Yesterday Miguel and I mapped out the cut int he wall for the electrical conduit + wire:
![image](https://user-images.githubusercontent.com/194400/167594737-8a0cb767-6f11-454f-9a75-12cbe9ab29fb.png)

Miguel made a hole in the wall for installing the bell: 🔨 
![image](https://user-images.githubusercontent.com/194400/167595611-6146bb54-9525-4802-9390-b1ed97bbff2e.png)

It's not as tidy as I would have liked ... 🙄 
He's no [Michelangelo](https://en.wikipedia.org/wiki/Michelangelo#Florence,_1499%E2%80%931505) when it comes to care/attention when chipping away at stone. 🙃 

In fairness this is what that section of the wall looked like before:
![image](https://user-images.githubusercontent.com/194400/167642989-1f35c176-1a10-41d1-9906-8d0eed663f33.png)

And when we removed the _old_ doorbell it left _most_ of the hole you see above:

![image](https://user-images.githubusercontent.com/194400/167643191-f24e2ca3-6b55-4d4f-a885-c941b4c1751c.png)

But Miguel will be filling in the gaps with fine cement prior to installation. 

Once it's mounted we will apply transparent silicone to:
a) weather seal it 🌧️ 
b) deter opportunistic theft  
(even sold for scrap it would be worth someone's effort to try to steal it ... 
let's hope the fact that it has motion detection and HD recording will help would-be-thieves think twice!) 

## Stealth Look? 😎 

I'm _tempted_ to give the white doorbell a **_Matte_ Black** paint job / makeover:
https://community.ui.com/questions/Installed-my-painted-doorbell/821ece15-93ef-4ac6-9da8-6ceeb8eef7bc
![image](https://user-images.githubusercontent.com/194400/167612862-21106974-f9d4-43e0-8afd-d3c5544e2a06.png)
But definitely not a blocker for getting this installed+working.

**Comment by nelsonic** [comment]
This issue has been parked waiting for the electricians to visit **`@home`** for over a month. ⏳ 
A _classic_ example of things taking _forever_ in Portugal. 

Seriously, the number of times I've considered doing an Electrician certification ... 💭 ⚡ 
But the course is in-person only in Lisbon ... https://www.inepi.pt/training/83/Electricidade
No jokes, if there was an Electrician course in Braga even in-person I would 100% do it 
and then just get Bruno to check my work.
I'm perfectly _capable_ of doing the work already; none of it is high-tension or particularly complex.
But given that we want to have _all_ the work certified so that we can get the building certified for ***`public`*** use,
we have to follow the rules. 🙄 

Anyway, assigning to @iteles to follow up with Bruno on getting one of their chaps over ASAP. 🙏

**Comment by nelsonic** [comment]
The electricians installed the doorbell but it says "weak wi-fi signal" ... 🤦‍♂️ 

![image](https://user-images.githubusercontent.com/194400/174999642-5b046a37-cbe2-4cea-927a-ace873d5fcf6.png)

We're living in the [dystopian] future where a doorbell needs Wi-Fi ... 📶 🙄 

I provisioned a new **Long Range** Access Point in the Library:
![image](https://user-images.githubusercontent.com/194400/174999909-5a7ac062-6461-48c4-a5f5-3f1ef4b5f9b5.png)

Which is the closest network port to the doorbell ... 
but it still wasn't enough to improve the signal strength. 😞 

So we need help from the electricians [again...] to install an outdoor wireless access point ... 💸

**Comment by nelsonic** [comment]
@iteles what are your thoughts on mounting the LongRange AP outside [out-of-reach of a casual thief]
so that the WiFi signal will reach the Doorbell? 💭

**Comment by iteles** [comment]
@nelsonic I put this in a text at the time but would we be able to run a cable from the library through to the entrance (eventually we could hide this under the floorboards and snake it up the entrance corner) and have the AP _inside_ against the glass (not much for it to go through)?

We could test it either if you have a cable to hand or by using the point that will be used for the entrance door just to test.

**Comment by nelsonic** [comment]
Happy to try anything we can in the short-term. But the probrem isn't the cable length per se ... 
rather it's the thickness of the (granite) exterior walls that almost completely block the signal. 
If we can position the internal AP such that it has line-of-sight with no obstructions 
then we we have a chance of decent signal
i.e: we need to raise it to the level where it can "see" out of the window. 

We have a cable we can use to do the test this evening after 👼 is asleep. 🤞

**Comment by nelsonic** [comment]
Can't believe so much time has elapsed since my last update on this. ⏳ 😮 ( 🤦‍♂️ )
I ordered an _outdoor_ wireless access point (AP) #207 
We can get the AP installed _today_ and then enable the doorbell. 

Meanwhile the Protect Chime is still sold-out [...as is virtually every other product on their site!!]
![image](https://user-images.githubusercontent.com/194400/206369464-6a310058-ede8-4d4d-a126-20e4c2d7eebf.png)

But with the Unifi App on your phone you will get an instant notification when someone rings the doorbell. 
We will install the App on all 5 iPhones in the house so _someone_ will always get notified.

**Comment by nelsonic** [comment]
After all that work to get the Outdoor AP setup #207 the doorbell still reports “weak Wi-Fi signal” … 😢

![IMG_4468](https://user-images.githubusercontent.com/194400/235439376-e682032c-5021-4606-a829-ca35bf5c2afc.png)
![IMG_4469](https://user-images.githubusercontent.com/194400/235439396-83ba5df9-3c51-4889-b13a-3183838171df.jpeg)

Let’s see if the firmware update does anything g. 🤞🏼

**Comment by nelsonic** [comment]
![Uploading IMG_4477.png…]()

captain obvious… 🙄

**Comment by nelsonic** [comment]
![IMG_4466](https://user-images.githubusercontent.com/194400/235440515-0dd573c9-f58c-4ca6-a6f8-d6ff10dd428b.png)
![IMG_4477](https://user-images.githubusercontent.com/194400/235440517-90c94c3d-2478-44f1-b8b6-5175f828fcf3.png)

captain obvious! 🙄

**Comment by nelsonic** [comment]
Doorbell is working even with the “poor Wi-Fi”.

The important bit is that it:
a) captures the doorbell button press
b) transmits the button press to the controller which in turn rings the chime (bell)
c) records the video of the person who is outside

![IMG_4502](https://user-images.githubusercontent.com/194400/235468007-7828472a-cbd6-4566-a445-195f20671bcf.png)

in this photo 👼 and I pressed the doorbell.
@iteles was in the kitchen and confirmed that it rang. Both of us got the notification on our iPhones and could see the video feed. 

This is the notification on homescreen:

![IMG_4503](https://user-images.githubusercontent.com/194400/235468864-8a998e34-435b-4bce-9e8e-05127f15aacc.jpeg)

> ⚠️Faces of loved ones anonymised for privacy.

I’m confident this is working.

# @iteles #please-test

**Comment by nelsonic** [comment]
The doorbell has successfully been used several times by delivery/post people in the last week. 
@iteles to confirm. 👌

**Comment by nelsonic** [comment]
@iteles when you view “Devices” in the “Protect” App installed on your phone, what do you see?

should be something like this:

![IMG_5045](https://user-images.githubusercontent.com/194400/236512838-0b37ad65-66cc-47da-acc5-1542f4d308b7.jpeg)
![IMG_5044](https://user-images.githubusercontent.com/194400/236512844-61ec46ca-0b23-466b-afe9-1d6dbbd2eaed.png)
