### ISSUE TITLE
Grass Trimmer

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#204]
@iteles please add this to the Leroy "project" list: 
https://www.leroymerlin.pt/Produtos/Ferramentas/conceito-bateria/bosch-diy/WPR_REF_82054038
![image](https://user-images.githubusercontent.com/194400/167968386-5e6fd185-3f6f-4b7e-bf5f-5b499c319e4e.png)

Thanks.

**Comment by nelsonic** [comment]
If we're unable to add it to the Leroy order (which will have a 10% discount) then this is Plan B:
https://ferramentas.pt/aparador-a-bateria-easygrasscut-18-230-bosch-06008c1a00.html?
![image](https://user-images.githubusercontent.com/194400/167968794-d7fb11d8-b8f6-4692-8e78-a69a998d95e6.png)

**Comment by nelsonic** [comment]
@iteles thanks for including in the Leroy order. 👍

**Comment by nelsonic** [comment]
https://m.olx.pt/d/anuncio/relva-brasileira-104-ps-guimares-IDBBmKG.html
![E650738B-A342-4E1D-A1B7-67719CBB2A69](https://user-images.githubusercontent.com/194400/174185076-b4accf00-1567-46df-afbc-25a4a3c52e7a.png)

just putting this here so I can close a tab

**Comment by iteles** [comment]
@nelsonic Am I right in thinking this still needs to be picked up from LM?

**Comment by nelsonic** [comment]
@iteles the trimmer has been in the garage for the past 10 days. [Miguel collected it when he went to fetch other supplies]

**Comment by nelsonic** [comment]
But we haven't actually _used_ it yet, because Filipe visited and cut the grass a couple of days prior ... 🙄

**Comment by nelsonic** [comment]
This has been used a few times now and works well. 
We still don't have a _system_ for when it gets done and by whom 
or a permanent place _store_ the trimmer ...
but it arrived and works.
so closing. ✅
