### ISSUE TITLE
Rout Groove + Install Induction Hob

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#206]
One of the things the IKEA kitchen planner/installers don’t tell you 
is that if you chose the **`80cm` induction hob**, 
you will be forced to **_manually_ modify** the cabinets.

This is because the cabinet below that contains the oven is 60cm. IKEA don’t make an 80cm oven. 

![D9501C19-8F73-48BB-BF3C-D25F3D3254AD](https://user-images.githubusercontent.com/194400/174441719-5a9e65f1-0c0a-4e48-b3c8-48a07b90be1b.jpeg)

Going to need to trim (rout) this part of the cabinet for the hob to fit:

![19700234-7CCB-42D0-8C43-CA4B5939FEDE](https://user-images.githubusercontent.com/194400/174441712-26a92806-68e7-4638-9a50-b956cd65647f.jpeg)

so we have to trim the top of the cabinet to make the hob fit. Not ideal, but there’s no way around it. 🙄

@iteles as discussed verbally, I feel that trying to find a *competent* person and *explain* this task to them is going to be more difficult than simply doing the work myself. 

Thoughts? 💭

Go-ahead confirmed by @iteles below: https://github.com/dwyl/home/issues/206#issuecomment-1159474921

![image](https://user-images.githubusercontent.com/194400/174443157-719941c1-a00f-44d0-8a32-47e63af119aa.png)

# Production Plan

+ [x] Get GoPRO and film (TimeLapse) this process so we have a record of it. 🎥 
  + [x] Charge GoPRO before starting anything! 🔋 
+ [x] Remove top drawer in right-hand cabinet to avoid damaging the drawer when routing 🪛 
+ [x] Remove Oven completely from housing as: 🔧 
  a) routing is going to make a _lot_ of mess and we don't want wood chips down the back of the oven because they are a fire hazard!  🔥 
  b) we'll need to connect the hob to the mains power that is conveniently _behind_ the oven and inaccessible! 🔌 
  c) removing everything is a good chance to _confirm_ that it was correctly installed and allows us to _document_ the process of re-installing it in case anything goes wrong in the future. 📝 
+ [x] Disconnect the wall outlet for the oven/hob at the consumer unit (electrical box switch) 💀 ⚠️ 
+ [x] Prepare the area for routing 💭 
  + [x] ***Measure! Measure! Measure!!!*** 📏 
+ [x] Run a test of edge router in the workshop to trial the cut before making it in the actual cabinet. **`YouOnlyCutOnce`**!! 🔪
+ [x] Perform the routing ***carefully*** 🪚 
+ [x] Test fit the Induction Hob to see that the routing worked 🤞 
+ [ ] Vaccuum the area and clean any debris! ⏳ 
+ [ ] Prepare the electrical cabling (the hob did not come with any connectors or cables!!) 🔌 
+ [ ] Attache the electrical cable to the hob and wall outlet ⚡ 
+ [ ] ***Test*** that the hob works (re-connect the electricity) ♨️ 
+ [ ] If it works, disconnect it again 🔌 
+ [ ] Re-connect and install the oven 

As you can see from this production plan, it's not a "quick fix".

**Comment by iteles** [comment]
Thanks for taking this on. I definitely feel you'll do a better job of this 😅

**Comment by nelsonic** [comment]
OK, cool. thanks for confirming go-ahead. 👌 
Going to add the production-plan (list of tasks) to the OP so I can map out everything that's required. ✅ 
I'm feeling that **`T2h`** might be _optimistic_ ... 💭 
But that's all the time I _have_ to get this done today before @Stephanymtr leaves. ⏳

**Comment by nelsonic** [comment]
Cut made:
![7BF64940-B653-4890-BECB-67BDB55F0DE4](https://user-images.githubusercontent.com/194400/174448352-0ddb4e16-0e28-41a7-9d8b-578f6ddd492f.jpeg)

Ended up using the saber saw as the router was creating mountains of dust and didn’t have a better result during testing.

![652EE05B-C99D-41D5-821B-10FE4F2F55B1](https://user-images.githubusercontent.com/194400/174448394-cae628d7-85e7-4958-b2a0-cd31cd49ce45.jpeg)

Test fit successful:
![35B8812B-4BC1-4750-9B49-EA35BF376533](https://user-images.githubusercontent.com/194400/174448404-cab9aba7-3e6e-465e-b547-795814a19637.jpeg)

working on electrical wiring now. 🔌⏳

**Comment by nelsonic** [comment]
Moments after I finished wiring the hob it tipped over and shattered … 😭

![DE1C811F-E267-470F-85E8-2D45CBEB4465](https://user-images.githubusercontent.com/194400/174456166-3650b3ae-0f53-4595-9e5a-9dec8b609002.jpeg)

verry, verrrrrryyyy annoying!!!! 😭

@iteles going to need the paperwork so I can claim on the warranty. Or at the very least get the glass top replaced by IKEA. 🤦‍♂️

**Comment by nelsonic** [comment]
Was 95% complete. Just needed to *gently* lower it into place and it would have been 100%. Unbelievably frustrating! 😭

**Comment by nelsonic** [comment]
I’m quite happy to make the phone calls to IKEA support and/or visit the customer service at the store. Obvs they are going to say that it’s not their problem cause they didn’t install the hob. 🤦‍♂️
so if I/we have to pay for a new glass top, it’s lame but whatevs. 🙃

**Comment by nelsonic** [comment]
I'm attributing this rather expensive lesson to [Murphy's law](https://en.wikipedia.org/wiki/Murphy%27s_law) and moving on. 😢  > 🙃 > 👍 > 🚀 
@iteles can we try and resolve this ASAP with IKEA, e.g. visit in-person today and see if they can help?
rather than wasting time on the phone with someone who will just bounce us around ...

**Comment by nelsonic** [comment]
@iteles did we get the quote for replacing the glass on the induction hob? 💭 (💸 🔥)

**Comment by iteles** [comment]
The glass was replaced and it is working flawlessly.

We need to:
+ Test the oven
+ Figure out why the right hand side drawer underneath is rubbing/sticking and resolve this.

**Comment by nelsonic** [comment]
Luckily this was fixed _ages_ ago. Closing. ✅

**Comment by iteles** [comment]
We didn't figure out what's happening with the right hand side top drawer though - can we use it? Or is constant use going to break something from all the friction?
