### ISSUE TITLE
Outdoor Wireless Access Point

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#207]
As noted in https://github.com/dwyl/home/issues/201#issuecomment-1162894643 the Doorbell needs WiFi 

Searching for "outdoor wireless access point" on the UI store gives us a few results but nothing "cheap" ... 🙄 
https://eu.store.ui.com/search?mockup=outdoor+wireless+access+point&q=outdoor+wireless+access+point
![image](https://user-images.githubusercontent.com/194400/175003462-11a63a27-3b2d-4b40-a25e-1e39f538a05f.png)

Apparently, the **`Access Point WiFi 6 Long-Range`** (**`SKU:  U6-LR`**) is **`IP54-rated`** for water and dust protection:
https://eu.store.ui.com/products/unifi-6-long-range-access-point-1
![image](https://user-images.githubusercontent.com/194400/175003794-bfd4d0aa-8bf5-4259-a9fe-3d5fd25b01b0.png)

So we could just use that outside. 💭 

_However_ ... if we're going to have to run an ethernet cable outside in any case ...
**note**: thinking of using the solar panel conduit ...
Then I'm thinking of getting an access point that has a secondary PoE output which we can use for a security camera #169 
https://eu.store.ui.com/collections/wireless/products/unifi-in-wall-hd
![image](https://user-images.githubusercontent.com/194400/175008523-7368d9f1-8d99-4d91-9195-bfb47e451372.png)

For our **_immediate_ needs**, I'm just going to **`use` what we have** rather than spend anymore cash. 
But in the future we will want to have the outdoor security camera [currently **out-of-stock _everywhere_!!**]
so having the PoE Output on the AP will save us having to run more cables and also save ports on the switch. 

> **Side-note**: every time I go on the Ubiquiti online store and see how expensive these products are i'm in pain ... 💸 🙄

**Comment by nelsonic** [comment]
https://eu.store.ui.com/products/unifi-ac-mesh-ap?_pos=3&_sid=b0c8fce7e&_ss=r&variant=32045200441453
![image](https://user-images.githubusercontent.com/194400/175011295-46038d66-953e-41c7-b208-80c5947ef848.png)

**Comment by iteles** [comment]
I've spoken to Bruno about running the Ethernet cable. He said this week will be impossible but he's going to check and I'm supposed to call tomorrow afternoon to check.

**Comment by nelsonic** [comment]
Sadly, nothing is in-stock right now... `#ChipShortage` ... 
Keep checking: https://eu.store.ui.com/

**Comment by nelsonic** [comment]
Given that no other outdoor Wifi AP/Antenna was in-stock I ended up ordering this one:
https://eu.store.ui.com/products/access-point-wifi-6-mesh
![image](https://user-images.githubusercontent.com/194400/206368377-35c07815-1d4e-49b4-a439-d25ffb595af5.png)

Yes, it's _definitely_ over-priced. but reviews are good and it should solve our issue with the Doorbell not connecting. #201 
Going to try and mount it with Miguel's help tomorrow afternoon. 
But it will still require the Electricians to visit to run a couple of Ethernet cables through the conduit and out of the Garage ...

@iteles could you please contact Bruno (electrician) and ask him when they might be able to visit either for **`T1h`** or for a full day if possible? 🙏

**Comment by nelsonic** [comment]
Busy testing the outdoor AP and getting full Wi-Fi - albeit at slightly lower speed - from across the street @home 🎉

![IMG_4186](https://user-images.githubusercontent.com/194400/235299311-8dad3bfe-4cd8-4d41-acb1-325230eb7698.jpeg)

![IMG_4185](https://user-images.githubusercontent.com/194400/235298883-f03aeca3-be7c-43ec-8892-547727a14772.jpeg)

more importantly the Outdoor AP has _almost_ direct line of sight to the doorbell #201 … I say _almost_ because the AP has line of sight to the gate, but then the doorbell is embedded in thick piece of Granite … 🙃

![IMG_4189](https://user-images.githubusercontent.com/194400/235299060-b1520e91-b22c-4980-bf13-bec1eb6a0873.jpeg)

which limits the bandwidth to ~9mbps:

![IMG_4190](https://user-images.githubusercontent.com/194400/235299351-8b722168-5ccf-421c-b9c4-f0c960c843df.jpeg)

this is quite a steep decline in bandwidth, but it should be *more* than enough to run a doorbell (with integrated camera…) 🤞🏼

**Comment by nelsonic** [comment]
The AP is not yet fully installed; it’s currently dangling off the network cable:

![IMG_4188](https://user-images.githubusercontent.com/194400/235299430-b9a42d7f-8214-4259-809f-4a3709c4dac0.jpeg)
![IMG_4187](https://user-images.githubusercontent.com/194400/235299432-0b50a174-1cda-447f-941e-9fd25203312e.jpeg)

I’m still testing the remaining CAT6 cables before mounting the wall bracket I made, but sadly, 2 of the cables appear to be faulty. 😢

Don’t know if you can see from this photo, but the connectors are mangled:

![IMG_4172](https://user-images.githubusercontent.com/194400/235299519-c53f1d10-71a3-4504-987d-6f3c7c148a6e.jpeg)

So I’m thinking of heading back to the electronics store to buy 2 new cables this afternoon. 💭

**Comment by nelsonic** [comment]
Confident the Outdoor Mesh AP is going to work though. So there’s some progress. 👌

**Comment by nelsonic** [comment]
And the up-side is that the whole south and west garden of the house has excellent Wi-Fi signal. 🛜🎉

**Comment by nelsonic** [comment]
Mounted the AP tonight after the munchkins were asleep. Too dark to take a photo. Will get one tomorrow morning. 👌

**Comment by nelsonic** [comment]
![IMG_4436](https://user-images.githubusercontent.com/194400/235437144-269376e1-04dc-41d7-990d-0d6ce2dfeb17.jpeg)
![IMG_4440](https://user-images.githubusercontent.com/194400/235437148-53d94d93-fda2-4cc5-9914-e88a98ee5bf9.jpeg)
![IMG_4446](https://user-images.githubusercontent.com/194400/235437149-7daebe4d-e7d8-4574-a108-717af60ebe80.png)

working flawlessly. ✅
Closing. 

# Next: #201 🤞🏼
