### ISSUE TITLE
Install Ladies Bathroom Cabinet

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#208]
The ladies bathroom currently has a shortage of storage space.

The wall-mounted cabinet that maximises the available space is the 80x96cm  **GODMORGON** cabinet:
https://www.ikea.com/pt/en/p/godmorgon-mirror-cabinet-with-2-doors-mirror-glass-10304355/

![7E120894-1BEC-4B40-B641-22959B99312F](https://user-images.githubusercontent.com/194400/176150621-a0c4414f-c71d-411d-878b-46acc8910852.png)

unfortunately it’s *insanely* expensive at **€279**!!

Luckily, last week when we visited IKEA we saw one in perfect condition (not a scratch on it!) in the bargains section:

![4AC0F39C-90A6-48E1-B679-47BE77E125D6](https://user-images.githubusercontent.com/194400/176150974-6762e648-7029-45fa-b7bf-d1cf2d5b4edd.jpeg)

obvs we bought it! And it has the added benefit of not needing to be *assembled*! 👌🏻

But now we need to wall-mount it. ⏳

# Todo

+ [x] do it!

**Comment by nelsonic** [comment]
Going to drill both mounting holes with 6mm bit. Then will gauge if the 10mm will work. 🤞⏳

**Comment by nelsonic** [comment]
Read the assembly instructions to see if they say anything about the weight of the cabinet …
https://www.ikea.com/pt/en/assembly_instructions/godmorgon-mirror-cabinet-with-2-doors-mirror-glass__AA-605081-8-2.pdf

Nothing. 🤦‍♂️

**Comment by nelsonic** [comment]
Doing a re-measure to be 100% certain that the holes I’ve marked are in the correct place. ⏳🤞📏

**Comment by nelsonic** [comment]
@iteles minor hiccup … if we mount the mirror so that it’s in-line with the top of the existing mirror, then the door will not fully open…

![DD6702C7-1EA4-4199-BD88-F24589C8F624](https://user-images.githubusercontent.com/194400/176154981-f40527ba-36df-439b-9e86-c28da646cf98.jpeg)

we could mount it higher up so that the door will fully open and not bash against the tap …

please advise. 🙏

**Comment by iteles** [comment]
Yes. Definitely mount it higher. No point in running the risk of it hitting the tap. 

Thank you 🙏

**Comment by nelsonic** [comment]
The height of the tap is 15.5cm of which 5cm is above the existing mirror:

![4884B581-D818-4AD0-B671-BF1D82D837C7](https://user-images.githubusercontent.com/194400/176163257-80550d94-3231-4e3f-9886-b2aba55844c3.jpeg)

so I raised the mirror by 6cm to be sure that it clears the tap.

**Comment by nelsonic** [comment]
@iteles Thanks for clearing/preparing the area of the holes after the holes were drilled:

![AFCF2014-8126-4D1B-93D2-2B6E486D8E95](https://user-images.githubusercontent.com/194400/176163528-d8f72c90-2102-410e-9c02-e784e529eb74.jpeg)

👌🏻

**Comment by nelsonic** [comment]
Cabinet mounted:

![20373CBA-50AC-4165-81FF-960392BE111B](https://user-images.githubusercontent.com/194400/176163763-1d67b517-b1e8-4066-9731-b719a72045e7.jpeg)

Door opens with 1cm clearance above the tap:

![37B150A4-C1D7-4E1B-986B-F6C43D6BC535](https://user-images.githubusercontent.com/194400/176163830-de687278-fe96-45e7-832d-73dfdcd7c088.jpeg)

@iteles over to you for review & next steps.

**Comment by nelsonic** [comment]
Ended up using the heavy duty 50kg per screw plugs and screws for *both* holes. 
*way* more confident that they will hold the weight of the cabinet and all the items in it.

Followed my plan of drilling 6mm pilot holes into the tiles, then did 8mm and finally 10mm to reduce risk of cracking a tile. 

No cracks. 👌🏻

**Comment by iteles** [comment]
Installed! Amazing 👌 

<img width="583" alt="image" src="https://user-images.githubusercontent.com/4185328/179323554-b13090a7-9c47-42c5-b030-c90c323a5ebe.png">
<img width="587" alt="image" src="https://user-images.githubusercontent.com/4185328/179323571-4a3e777c-fba2-4d95-9cef-c59fae7c3478.png">
<img width="595" alt="image" src="https://user-images.githubusercontent.com/4185328/179323588-1fa4b041-fa7a-4201-842c-d06339b82631.png">

**Comment by nelsonic** [comment]
Thanks for capturing this and confirming complete. 👌🏻
