### ISSUE TITLE
Library Armchair

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#211]
At present the library is just books. 📚 
There's nowhere to sit when reading a book so we end up sitting on the floor; not the most comfortable. 🙃 
Soooo ... thinking of getting an armchair to sit and read in. 💭 

**`IKEA STRANDMON`** Armchair with footstool in **Nordvalla dark grey** 
https://www.ikea.com/pt/en/p/strandmon-armchair-and-footstool-nordvalla-dark-grey-s39483907/
![image](https://user-images.githubusercontent.com/194400/205432082-b6a6f1e6-2977-4953-80a2-63133a899d5d.png)

This is the same chair as @carolrmc has and it's a **_very_ comfortable** reading chair. 🪑 
It's not the _cheapest_ but also not the most expensive chair in the world.

Another option is a **`POÄNG`**: 
https://www.ikea.com/pt/en/p/poaeng-armchair-birch-veneer-skiftebo-dark-grey-s59388457/
![image](https://user-images.githubusercontent.com/194400/205432459-9c915852-ceb0-47dc-85e1-483f6935ad53.png)

Thoughts? 💭

**Comment by iteles** [comment]
Pqe inclined to make reading spots with cushions on the floor _inside_ the library and build out the under-stair reading area. 

This armchair is SUPER comfortable and I love it (though I never sit in it at @carolrmc's house because of the 🐱), I think it's just a question of placement.

**Comment by nelsonic** [comment]
@iteles given that the chair with footstool is "**SUPER comfortable**",
would you ***use*** it? e.g: once a month for some _You-and-your-thoughts time_<sup>TM</sup>? 

Would you feel any _better_ about it if we lowered the cost by buying it second hand from OLX?
https://www.olx.pt/d/ads/q-STRANDMON/
![image](https://user-images.githubusercontent.com/194400/205479433-0b0f4bf6-77bd-4c60-b045-d5cbeec86c46.png)

https://www.olx.pt/d/anuncio/poltrona-ikea-strandmon-IDHsR66.html
![image](https://user-images.githubusercontent.com/194400/205479371-041432e0-ea8a-434a-91bd-2c4eeb47af7a.png)

in Porto and looks "as new". 🆕 
We could ask @LuchoTurtle to collect it for us with Tia S' Van (and bring it next time he visits Braga...) 🚗

**Comment by iteles** [comment]
Oh my problem isn't the cost, it really is the location. 

But yes, if we can get it second hand this would be waaaaay more aligned with our values and we should 100% do it 👌🏻

**Comment by nelsonic** [comment]
@LuchoTurtle over to you, would you mind doing a pickup for us? 🙏

**Comment by LuchoTurtle** [comment]
Idk when I'm going to be visiting y'all but when I do, for sure 👍

**Comment by nelsonic** [comment]
Ok, if you don't know when you're likely to be back in Braga, we can put this on temp hold ...

But if you think you can do us the favour of collecting the Chair 
and bringing it over some evening this week,
it would be nice to take advantage of the **`€120`** deal.

Obviously only if you think it would take **`T2h`** to _collect_ and drive the chair to Braga.
Cause if it takes any longer than that we would be losing money 
when factoring ["Total Cost of acquisition"](https://en.wikipedia.org/wiki/Total_cost_of_acquisition) (Cash, Time, Petrol, Tolls & [Opportunity Cost](https://en.wikipedia.org/wiki/Opportunity_cost))

I agree with Inês, that in terms of total carbon/natural resource usage 
buying it second-hand is a no-brainer.

But if the chair is "only" **`€199`** (***`new`***):
https://www.ikea.com/pt/en/p/strandmon-wing-chair-nordvalla-dark-grey-20343224/#content
![image](https://user-images.githubusercontent.com/194400/205514445-893806f0-972b-4ce0-b914-c789136b21a8.png)
And we would get **`23%`** (VAT / IVA) back for buying it through a Biz. 
The cost to us is **`€161.79`** i.e. **`€41.79`** more than the **`€120`** second-hand chair.

If we value Luis' time at ("just") **`€20/hour`** then we'd _immediately_ lose money if it took more than **`T2h`**.
Then factoring in **`~€15`** in Diesel fuel and **`€10`** in road tolls for the round-trip,
it becomes _more_ expensive to buy the second hand chair. 

> I know this is may appear like a planet-unfriendly way of thinking, 
but this is precisely how ["successful"] business people are trained to think. 

If we factor in communication/organising time of **`€20 mins`** at @iteles' or _my_ standard rate 
then buying a second-hand chair becomes _laughably_ uneconomic.

**Comment by LuchoTurtle** [comment]
Even if I can't get there this week, I can still pick it up while there's the 120euro deal going on and have it here until I can drive it there (perhaps the weekend works). Vicente uses the car so it should be "free-er" on the weekends for me to use it for longer time spans i.e going to Braga.

**Comment by nelsonic** [comment]
Sounds good. If you don't mind contacting the chap selling it on OLX to ask if they still have it that would be a first step. 🙏

**Comment by LuchoTurtle** [comment]
Just did. It's still available. He's available whenever 19h+. If yall want and are happy with the condition, I can drive by and pick it up tomorrow or Tuesday. I'll then drive to Braga probably on Saturday or perhaps Thursday.

I can't today because Vicente is using the car.

**Comment by nelsonic** [comment]
OK. as soon as you have access to the **`VW Sharan`**, please confirm it's still available. 👌 

Difficult to tell from the photos if the condition is "as new":
![image](https://user-images.githubusercontent.com/194400/205517529-b383518b-efc1-4a46-af63-4265a71699f7.png)

**Comment by LuchoTurtle** [comment]
Even though I arranged with the guy to pick it up today, I just called him and he said it was sold.

:|

I guess you can either try to get another one second-hand or buy a new one.

**Comment by LuchoTurtle** [comment]
Though you have some Poang IKEA chairs on sale and they are cheaper. I think it's the same model you have in the living room.

https://www.olx.pt/d/anuncio/cadeira-poltrona-pong-IDCQ6M5.html

<img width="528" alt="image" src="https://user-images.githubusercontent.com/17494745/205724215-1a77d8ac-b5f6-47f1-839b-a5a9ebcea2b3.png">

This is retail 
<img width="637" alt="image" src="https://user-images.githubusercontent.com/17494745/205724321-10e45a3b-140f-4a4b-9b8a-1c3a61b98b11.png">

**Comment by nelsonic** [comment]
>"_Even though I arranged with the guy to pick it up today, I just called him and he said it was sold._" 

Lame. 🤦‍♂️ 
Don't know what the "lesson" is here ... 💭 
"_never trust random strangers on the internet_" ... 😜 
(that's pretty good advice for live in general ...) 🙅 

A day later and the seller still hasn't bothered to remove the advert:
https://www.olx.pt/d/anuncio/poltrona-ikea-strandmon-IDHsR66.html
<img width="1328" alt="image" src="https://user-images.githubusercontent.com/194400/205884686-c61df4c1-9ac2-45bf-b910-1107d75c9add.png">
This is why we can't have nice things. 
There needs to be a blockchain for all goods and services sold in the world so that sales are all tracked and people don't have to waste time like this!

Yeah, I love the _comfort/ergonomics_ of **`POÄNG`** chairs. 🪑 
But they are difficult for older people to get out of; they topple. 👵 
So we either "mod" a **`POÄNG`** to be more stable ***or*** spend a bit more money and get a **`STRANDMON`**. 💸 

Sadly, as accommodating/helpful as @LuchoTurtle is with this, I _really_ don't think it's a _good_ use of his time to be chasing second-hand furniture. 

Going to order a ***`new`*** one. 
And will keep an eye out for second-hand ones within a 20min drive of @home if we decide to get a second one.

**Comment by nelsonic** [comment]
https://www.ikea.com/pt/en/purchases/1325755875/ 🛒 💸

**Comment by iteles** [comment]
I mean... also in Porto. And yellow. 

There's still time to cancel your order...

https://m.olx.pt/d/anuncio/poltrona-amarela-IDHpKsK.html

![image](https://user-images.githubusercontent.com/4185328/206291423-4dff891d-562f-49ee-9011-5bfcb12d1091.png)

**Comment by nelsonic** [comment]
@iteles yeah, I looked at dismantling the chair for transport and it's _relatively_ easy ...
Do you want to axsk the seller if they still have it available?

**Comment by iteles** [comment]
David had the jeep with him doesn't he? 

This is the chair:
![image](https://user-images.githubusercontent.com/4185328/206691258-9d8c870e-dc65-456a-8450-cab8972afd83.jpeg)
![image](https://user-images.githubusercontent.com/4185328/206691294-7ff0317e-f6c9-46b4-9a01-243b4fbb9dbf.jpeg)
![image](https://user-images.githubusercontent.com/4185328/206691314-e1c72cf8-6ecf-4ff1-b2f8-9c9a7256e128.jpeg)
![image](https://user-images.githubusercontent.com/4185328/206691333-88845889-1c12-4fb7-93ca-193905e7117d.jpeg)

Already organising to pick up tonight or Sunday depending on car  availability. 
Pick up location is https://goo.gl/maps/hnWduD46GeRB2zEp7

**Comment by nelsonic** [comment]
@iteles cool. LGTM! 👌

**Comment by nelsonic** [comment]
Best money we've spent in a _loooong_ time! Zero Regrets. ❤️ 
<img width="759" alt="image" src="https://user-images.githubusercontent.com/194400/208042025-3c8f3b85-9eaa-4d38-a0d2-ab44a9a83ec0.png">

Thanks for humouring me. 👌 

P.S. Yes, the bookshelf is a mess. 🙄 
Maybe @Stephanymtr can help organise it over Xmas? 📚 💭 #216
