### ISSUE TITLE
Fix Wi-Fi Quality issues

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#222]
The Wifi Network @home has been "patchy" for the last few weeks. 
I've axsked other people to open this issue but everyone appears to be too busy ... 

<img width="574" alt="image" src="https://user-images.githubusercontent.com/194400/214863783-f87e9206-0026-45fc-a4bf-0d1ed89e5e61.png">

So I'm opening this as a placeholder to re-build the network from scratch (full reset)
and document each step along the way.

**Comment by iteles** [comment]
On this, I'm having issues getting Wi-Fi in the kitchen, dining room and in the two corner bedrooms upstairs.
It seems to show as having wifi but in reality there is no connection.

**Comment by nelsonic** [comment]
@iteles thanks for confirming. 👌 
You may not _recall_ but I've asked 3 people to open this issue ... and nobody seems to have the ***`time`*** ... 🤷‍♂️

**Comment by iteles** [comment]
Not the same but related:
I've never had wi-fi issues in the basement office area before but today, I get full wi-fi signal but this is my speed 🐌 
<img width="672" alt="image" src="https://user-images.githubusercontent.com/4185328/219373676-27d78b66-44ac-4073-b655-32528572e7e1.png">

**Comment by nelsonic** [comment]
@iteles thanks for commenting. 👍 
In the first instance try the "5G" version of the network you're connected to. 
I currently get **`~390 Mbps`** sitting **`2m`** from you:

<img width="1093" alt="image" src="https://user-images.githubusercontent.com/194400/219374289-323e103b-7b33-4c0d-8faa-dbf1d336e4b2.png">

I would _really_ like to dedicate some time to resetting and documenting the WiFI Setup. ⏳ 
Sadly, if nobody thinks it's a priority then it _never_ gets done. 😕

**Comment by iteles** [comment]
Not as good as you, but better, thanks!
<img width="717" alt="image" src="https://user-images.githubusercontent.com/4185328/219378181-508f647a-9615-4ec5-9762-a027a3fe5d56.png">

**Comment by nelsonic** [comment]
OK. the _next_ step is for us to setup an Access Point in the Studio 
***or*** for you to connect via ethernet. 

I can set this all up. but it takes time. ⏳

**Comment by iteles** [comment]
I don't think we need another AP in the studio, 120Mbps is plenty. 

Much more important to get the AP in the dining room and on the top floor working properly 👌🏻

**Comment by nelsonic** [comment]
Network completely reset #229 and now the Wifi quality on every AP is "excellent":
<img width="1661" alt="image" src="https://user-images.githubusercontent.com/194400/235014603-89daba77-5fc9-4347-8c03-b63f575f9061.png">

Using the latest version of the Unifi Network App:
<img width="574" alt="image" src="https://user-images.githubusercontent.com/194400/235014647-004616f6-6c33-4100-9211-182e288c8589.png">

Means that each AP now automatically checks for the lowest traffic channels and switches them. 
That means the Wifi should be consistently good for longer. 
But don't worry, I'm not going to stop there!

**Comment by nelsonic** [comment]
on the _internal_ network I get:

<img width="808" alt="image" src="https://user-images.githubusercontent.com/194400/235014885-8c319cba-a221-4238-80b0-3ce82b4ea1a1.png">

and on the _external_ network I get:
![image](https://user-images.githubusercontent.com/194400/235014980-c988652f-1e47-4a8c-a202-979f22c4c855.png)

Not quite the 1Gbps we are _paying_ for ... 🙄 
But good enough for our needs. 👌 

@iteles over to you to test tomorrow. 🙏

**Comment by iteles** [comment]
Working great, including in the dining room 🤩

This issue can be closed aS far as I'm concerned 👏🏻

**Comment by nelsonic** [comment]
@iteles yesterday you mentioned that your iPhone was occasionally failing to connect to WiFi. 🤷‍♂️ 
Could you please provide more detail? 📝 
Do we need an additional Access Point in a specific part of the house? 📶

**Comment by iteles** [comment]
This is linked to my phone and not the Wi-Fi. My computer was picking up the network just fine in the same spot.

**Comment by nelsonic** [comment]
Ok, So a separate issue. 👌
All @home APs are now “excellent” including outdoor! 

![IMG_4435](https://user-images.githubusercontent.com/194400/235436695-eab46883-8b38-4a4f-aa83-fe6c1ae140af.png)

closing for now. ✅
If you have any other Wi-Fi issues, please re-open. 🛜
