### ISSUE TITLE
Soil Auger

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#236]
@iteles as briefly discussed verbally, we are going to need an Auger for our work @home this week. 

Landim has a good one that they use for drilling soil when putting in posts for vines. 
they aren’t using it right now because no posts are being installed. 

Could you please call Ricardo and ask if we can borrow it for a few days?

In PT it’s called: 
“Perfuradora de Solo a Gasolina”

For now we cannot justify spending the money to *buy* this tool for ourselves because we only need it to drill a few holes ~20.
But *manually* digging these holes will take 5x longer than using a machine so if we can borrow one, we totally should. 

In future I plan to buy one when we need to plant lots of trees (“Phase Three”) but it will be Electric not fossil fuel based … 🙃

once you get agreement from Ricardo that we can borrow it, we will go collect it with the Van. 🚚

**Comment by iteles** [comment]
Spoke to him this morning, he says it needs tuning which he'll try to do tonight. 

Then tomorrow morning we agree a time to pick it up as he has to be there to show us goes to operate it. 

He says it fits in the trunk of a car so the van might not be needed.

**Comment by nelsonic** [comment]
@iteles thanks for calling him. Great that he will tune it ahead of our use and give us a quick tutorial. 👌
We’re taking the Van because we want to bring back some other construction materials we left there. 🚚

**Comment by iteles** [comment]
Do I need to contact Ricardo to ask when he needs it back?

**Comment by nelsonic** [comment]
@iteles `R` said he would call you if he needs it. But said he hasn't used it in _ages_.

**Comment by nelsonic** [comment]
@iteles we're needing the `auger` again this week.  🕳️ 
We've used the one from Landim the past 3 times but each time it's "cost" us
`T4h` of `M` time which has **`Opportunity Cost`**; not doing other more useful work! 
> He doesn't _appear_ to go _straight_ there/back to collect and drop it off ... 🐌 
It _should_ take `~T40min` (**`35 km`**) each way x 4 journeys ... one round-trip to collect and another to drop-off. 
`M` also wastes time (and our money) getting ***`Non-renewable Fossil Fuels`*** (`Gasoline`) ⛽ 🦕 🔥  to power the `auger`,
but that has only been `10Litres` so far so it's the _least_ of our worries but still lame to waste dino-juice ...
He's also adding **`140km`** to our `Van` each time we use it. 🙃 

Anyway, I feel this is all a _huge_ waste of time and we should just _own_ an `auger`; 
_specifically_ an **`electric`** one that doesn't consume 
https://www.einhell.pt/en/p/3437000-gp-ea-18-150-li-bl-solo/
<img width="1230" alt="image" src="https://github.com/user-attachments/assets/c211b621-52c2-40a6-aed5-8f1235bae66d">

![image](https://github.com/user-attachments/assets/5a312ca4-be02-44a1-9191-9d0984f1dbfb)


https://www.amazon.es/dp/B09NQJJH77/ref=asc_df_B09NQJJH77/
<img width="1589" alt="image" src="https://github.com/user-attachments/assets/53e32e03-e959-4619-a59e-3301971396ef">

If we assume **`T4h`** is _wasted_ each time `M` has to `get` + `return` the `Landim` one,
And we're still going to need to borrow it 3 more times that's **T12h** of **`M` time** i.e. **`1.5 Days` Wasted**!
**_Most_ importantly** given that our [burn-rate](https://github.com/dwyl/home/issues/244) and opportunity cost of _not_ finishing `Braga` is **`€300/day`** 💸 🔥 
we should do _everything_ we can to avoid _wasting_ the time of our primary work person (bottleneck)!
See: https://en.wikipedia.org/wiki/Theory_of_constraints

So as far as I'm concerned this is a no-brainer purchase that will _save_ us it's full cost with 2 uses. 
_And_ if we end up buying [`land`](https://github.com/dwyl/phase-three/issues/116) we will use it _extensively_ for planting trees and fence posts! 🌳 

Also need _two_ batteries for it: https://www.amazon.es/dp/B07NJ727HW/
<img width="1564" alt="image" src="https://github.com/user-attachments/assets/beccd314-c9ac-4632-be41-bb06aced5095">

Already have the `POWER X Charger` so don't need to buy that. 
_Could_ get the _`FAST Charger`_ but honestly don't think it will be necessary 
as we only tend to do 10 holes a day and then can charge over-night. 

These batteries work for other `Einhell` battery-operated products like our hedge trimmer / chain saw. 

<img width="776" alt="image" src="https://github.com/user-attachments/assets/276ba49a-9039-4bb5-b528-991133dbeb3c">

Executive decision. Placing the order. 🛒 
This will _save_ us cash in terms of overall burn-rate/opportunity-cost _immediately_. 
Wish I had done this sooner!! ⏳ 💸 🔥

**Comment by iteles** [comment]
I will still look to get the auger for this week ahead of the one you have purchased arriving.

**Comment by iteles** [comment]
![image](https://github.com/user-attachments/assets/e4383b7c-86e6-4757-bebd-6d4559829e67)

The keys that I went and got copies of when I went to Porto for Avó Lidia's funeral are on the iQ set of keys.

**Comment by nelsonic** [comment]
The _electric_ auger arrived last week and was put to use immediately. Does the job well. ✅
