### ISSUE TITLE
Breadknife Snaped 🔪💔

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#248]
Our J.A. Henckels international 8” bread knife fell off the kitchen counter onto the tile floor and snapped:

![IMG_8627](https://github.com/dwyl/home/assets/194400/57c42895-cd09-4b64-8b90-fe74f8d656e5)

![IMG_8628](https://github.com/dwyl/home/assets/194400/4f47fa08-6363-4d80-9603-432905d64ecd)

very disappointed 😔 

https://www.amazon.es/Henckels-Classic-Precision-Cuchillo-pulgadas/dp/B08VJKNDHF/ref=sr_1_2?__mk_es_ES=ÅMÅŽÕÑ&crid=31QWWJ367EA1&keywords=HENCKELS+Classic+Precision+Razor-Sharp+8-inch+Bread+Knife

@iteles given that this knife was meant to be a “forever” one and didn’t pass a drop test, should we just get an IKEA one? 💭

**Comment by nelsonic** [comment]
https://www.ikea.com/pt/en/p/ikea-365-bread-knife-stainless-steel-70283519/
![IMG_8640](https://github.com/dwyl/home/assets/194400/410cec3d-c364-40db-bfe2-eb181afa537a)

**Comment by iteles** [comment]
Sure. Our IKEA knives have lasted fantastically well.

Just sad as this was a gift from friends!

**Comment by nelsonic** [comment]
@iteles indeed. very sad. never in a million years would I think a knife falling off a 90cm counter top would break like this. 😢

**Comment by nelsonic** [comment]
@iteles IKEA tonight with a pit-stop at Luna Kids? 💭

**Comment by iteles** [comment]
Bought it. Closing.
