### ISSUE TITLE
Under Sink Storage

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#249]
At present the storage under the “long” kitchen is dire. 

Depth: 585
Width: 764

![IMG_8744](https://github.com/dwyl/home/assets/194400/60316dee-d295-4006-8ebe-90663125278a)
![IMG_8743](https://github.com/dwyl/home/assets/194400/46297d06-1c97-40f7-9884-89a503adfce4)

I propose placing a shelf there to allow for organising. 

@iteles any objections?

**Comment by iteles** [comment]
None. 👍

**Comment by iteles** [comment]
Excited about this now 😆

**Comment by iteles** [comment]
It's done! thank you, much easier to find stuff now.

**Comment by iteles** [comment]
Yea, I maintain that it was a priority 3 but it sure is nice to have 🫶🏻
