### ISSUE TITLE
chore: `Home` network seems to be down

### ISSUE THREAD

**Issue by LuchoTurtle** [dwyl/home#252]
related to #222 (and maybe #229)

I've been working on the `MEO-26A...` wifi network because `home` seems to be down (I've noticed this on the last floor, as well).

<img width="449" alt="image" src="https://github.com/dwyl/home/assets/17494745/e6297bbe-9a35-49d3-8dd1-bdc507edc231">

I don't know if a simple reset would solve this or not just providing feedback 👌

**Comment by LuchoTurtle** [comment]
<img width="396" alt="image" src="https://github.com/dwyl/home/assets/17494745/cd863afd-d8d4-459b-a454-d01e9223c204">

Even `MEO` appears to be struggling.

**Comment by nelsonic** [comment]
This is very strange. Just went upstairs and the access point was unplugged. 🤦‍♂️
Feels like I need to make an acrylic lock box to prevent the APs from being messed with … 🥩

**Comment by LuchoTurtle** [comment]
Can confirm I can properly connect to `home` now.
Closing this off.
Thanks!

**Comment by nelsonic** [comment]
![IMG_1058](https://github.com/dwyl/home/assets/194400/728ac690-2a89-45a1-901a-ae2589110953)

In future, if you don’t mind, please do a physical (visual) check if the access point just to confirm that someone hasn’t unplugged it. 👌

and thank you for opening this issue. 🙏
