### ISSUE TITLE
Doorbell offline

### ISSUE THREAD

**Issue by iteles** [dwyl/home#262]
About 2 weeks ago, our doorbell stopped _ringing_, although we still got a notification on our phones.
I have since figured out that this is because the plug it's plugged into has stopped working.
I have the electricians coming in hopefully soon to sort this out.

In the last few days however, it has stopped ringing altogether and yesterday I noticed the doorbell itself outside said `offline`.
I didn't have hands to take a photo but will add one here.

**Comment by nelsonic** [comment]
Doorbell has been working flawlessly for the past couple of months since I did the Network (PiHome) shift https://github.com/dwyl/learn-computer-networking/issues/20 
Closing this issue as there is nothing further to do given the OP doesn't have a checklist.

**Comment by iteles** [comment]
It hasn't been spearing as a notification on my phone, I need to figure that out.
