### ISSUE TITLE
Board Games Storage 🎲 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#263]
At present our board games are spread over various places in the leisure room creating clutter.

We need a way to Display & Tidy our games that:

+  [x] A) keeps them all in the same easily accessible place.
+  [x]  B) out of direct sunlight so the boxes don’t get sun-bleached/wrecked
+  [x]  C) out of the reach of small children (several games have tiny - choking hazard - pieces …)

I propose building a shelf system out of basic (mostly scrap) 10mm plywood and mounting it to the wall above the speakers.

**Comment by nelsonic** [comment]
Thinking of mounting the shelves on the north east wall below the toy box shelves:

![IMG_1593](https://github.com/dwyl/home/assets/194400/cf438e3e-cde0-4ecb-977f-4e70f354bdc7)

**Comment by nelsonic** [comment]
Went ahead and made a shelving unit measured to the size of games boxes: 

![IMG_2201](https://github.com/dwyl/home/assets/194400/e26bb486-7b97-4123-ba67-8d81ebb91e36)

got some help from our munchkin to put plugs in the holes I had drilled:

![IMG_2199](https://github.com/dwyl/home/assets/194400/da7b3247-84c8-4c74-95f6-e297d81d743f)

**Comment by nelsonic** [comment]
Populated with games:

![IMG_2202](https://github.com/dwyl/home/assets/194400/5292c48c-f4eb-45d9-83c6-d157c871d6d7)

@iteles are there any other games around the house you want to store here? 💭

also, feedback welcome. 🙏

**Comment by iteles** [comment]
I have 2-3 kid friendly games that are actually with the rest of the children's toys for rotations which I could move down here 👌🏻

No other feedback, we don't need more room than this. As long as they're out of the sun 👌🏻

**Comment by nelsonic** [comment]
Cool. My biggest issues - besides the clutter - was 👦 opening a box with tiny pieces and losing them around the room and then 👶 finding and putting them in mouth and potentially choking. So I made the decision to just build _something_. 
We can easily do something completely different in the future if we discover something better. 
But yes, this location is devoid of natural light. 🌥️
