### ISSUE TITLE
Temporarily block holes in entryway

### ISSUE THREAD

**Issue by iteles** [dwyl/home#267]
Both `A`s have picked up the annoying habit of digging their hands into these holes and filling the entryway (and themselves and their airways) with dust.

<img width="1246" alt="image" src="https://github.com/dwyl/home/assets/4185328/68ec092e-c48a-4b4d-a0ab-4363416371d8">

This seems like great work to finish in the few days when the kids will not be home in April, but until then, can we do something to block these holes from their little hands? Tape won't do the trick as they just pulled it right off.

Any bright ideas @nelsonic 💡 ?
Obviously not worth spending more than 30 mins on this as it's very temporary, but is a daily annoyance (even though they love it).

**Comment by nelsonic** [comment]
@iteles as you may be aware `M` has been working on the structure that fits in these holes these last couple of days. It's 95% done. If there's another rainy day on Monday, it will be _finished_. Like not even worth you opening an issue for it. 
For ref, the issue this relates to is: https://github.com/bmhco/shared/issues/36

**Comment by nelsonic** [comment]
https://github.com/bmhco/shared/issues/36#issuecomment-2070099354
