### ISSUE TITLE
Refrigerator ice maker having a moment/not working

### ISSUE THREAD

**Issue by iteles** [dwyl/home#269]
Our ice maker is having a moment and appears to be making the _occasional_ ice cube (like 5 a day) but generally not working.

I think you determined @nelsonic that this sometimes happens when the freezer is kept open for too long.

I don't know how to reset the ice maker to see if that resolves the issue...

![image](https://github.com/dwyl/home/assets/4185328/24c4a38a-ef5d-4a86-9c56-f8d51df8b36e)

**Comment by nelsonic** [comment]
@iteles thanks for opening this issue to capture. 👌
I can take a look at it later when I’m back @home ⏳
But in the first instance I think the fridge just needs to be power-cycles (turned off & on again) to reset it. 📴🔛
Also, we should consider changing the water filter. 💭

**Comment by nelsonic** [comment]
The ice-maker has been working fine these past few weeks including use by guests. 🧊 ✅ 
Closing. If you have trouble with it again, please re-open with _specific_ observations. 👌
