### ISSUE TITLE
Bug: incomplete Recycling System -> Big Fine! 💸😢

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#276]
@iteles Today while you were away from @home two ladies from Agere (the environmental/water/waste management company responsible for collecting trash & recycling) paid us a visit to serve you a fine in-person… 😬

![IMG_4034](https://github.com/dwyl/home/assets/194400/4f8f02fd-cac4-43bf-b315-30ed9c59f2ee)

There’s quite a lot of people ***legalese*** in the paperwork: 📑 

![IMG_4035](https://github.com/dwyl/home/assets/194400/36ca40f1-3199-48a5-b2f8-74f446a81cba)

but the included Photo of packing for a book standing *next* to the recycling bin_appears_ to have your name and full address on it:

![IMG_4036](https://github.com/dwyl/home/assets/194400/f22a7209-dd2d-4b5b-9bcb-1afd5defd009)

so there’s not much you can do to argue the packaging “isn’t mine” … 🙃
What you _can_ do about it:
Go to the Agere office (near the City council - Câmara municipal) and plead your case. Specifically that we suspect the bins must have been full, as they are often overflowing - I can dig-up a photo of this - and our special learning needs person (DT) must have left the packing _next_ to the bin as many other people do. 
suggest you take 2️⃣ with you and play the “Tired Mom with adorable baby” card. The ladies that served the paperwork said if you plead with the administration they might even wave the fine for being a “first offense” and not being your fault … 🤷‍♂️

oh and you have 10 days to get it sorted before they release the hounds! 🐕 (i.e. the fine goes up and you could even face a court appearance… so don’t procrastinate on it!)

but .. we *CANNOT* let this happen again!!
Once you’ve resolved the fine part, we _must_ have a detailed recycling checklist that includes ***ALWAYS*** anonymising any personally identifiable information!! 📋 ✅

also, DT - and whoever else ends up doing the recycling in future - needs to be aware of the consequences of their actions! If the packaging had our *company* name on it, making it “business” (pessoas colectivas) the ***minimum*** fine would be **€1,250**. **YES**, you read that correctly ***MINIMUM***!! 😱
I already anonymise packing addressed to me (or the biz) *immediately* on receiving it … but this needs to be a documented *system*! If we ever get another one of these letters/fines I will be a _very_ sad panda. 🐼😭

**Comment by nelsonic** [comment]
@iteles just a friendly reminder that this is ticking clock ... ⏳

**Comment by iteles** [comment]
I'm pretty sure this was Meire. I've seen DT do the recycling and she not just puts it in the bins but pushes it down quite well.

But yes, definitely appreciate the reminder.

**Comment by nelsonic** [comment]
guessing you got to the bottom of this? 💭 
is there a written system _anyone_ can follow so it doesn't happen again? 📝

**Comment by iteles** [comment]
I just emailed them within the allocated appeal time to the email address on the letter and said it was someone who was helping us and reminding them it's a 'first offense'. I never heard back 🤷🏻‍♀️

**Comment by nelsonic** [comment]
Might want to send a follow-up ... 💭

**Comment by iteles** [comment]
Ball is in their court. I'm closing for now.
