### ISSUE TITLE
BUG: downstairs shower leaking 💧💦⏳💸

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#281]
Downstairs shower is leaking/dripping water: 💧💦🪣

https://github.com/user-attachments/assets/0929a53b-faea-40b6-9587-ae2523423960

At this rate it will start costing us money quite quickly. 💸
And it’s lame to be wasting water like this … 😢
@iteles could you please 

+ [ ] call the plumbers 🧑‍🔧 📞
  Find out if they can come fix it ASAP. ⏳🙏

(Or please forward the contact details of the plumbers and I’m happy to call them out … 👌)

**Comment by nelsonic** [comment]
@iteles don't know if you saw this. ⬆️ 
The dripping continues and it basically tortures me each time I go to the bathroom ... 😞 
If you can share the contact details of the plumbers I'm happy to call them. 📲

**Comment by iteles** [comment]
We don't have a plumber. I'll get one.

**Comment by iteles** [comment]
Coming tomorrow at 14h00, only option available.

**Comment by nelsonic** [comment]
Thank you. 🙏

**Comment by nelsonic** [comment]
Plumber visited today and _appears_ to have fixed the leak. 🤞 
@iteles could you please share contact details privately so I have them as a future ref. Thanks.

**Comment by nelsonic** [comment]
This was fixed along with re-sealing the shower. Should be good for another few years. ⏳ 🚿 👌
