### ISSUE TITLE
Signage: Food Grade and Non-Toxic Wood Varnish

### ISSUE THREAD

**Issue by KrishaD20** [dwyl/home#287]
So, while discussing signage with @iteles, she suggested that we look for a food-grade, non-toxic varnish, especially if we plan to place some signs in the kitchen.

When finishing laser-cut wood signage, particularly if it will come into contact with food or be used in environments where safety is a priority, choosing a food-grade, non-toxic varnish is crucial.

Here are some of the best options:

- **Pure Tung Oil**

![Screen Shot 2024-08-28 at 11 58 46 AM](https://github.com/user-attachments/assets/539d80a2-51fe-4a6c-843d-674a02ffe71d)

_Features_: Made from the pressed seeds of the tung tree, this oil is 100% natural, non-toxic, and food-safe. It penetrates deeply into the wood, providing a durable, water-resistant finish.

_Application_: Apply multiple thin coats using a brush or cloth, allowing each coat to dry thoroughly.

_Finish_: A soft, satin-like finish with a slight luster, offering a low to medium gloss.

_Pros_: Ideal for those who prefer a natural, non-toxic option that enhances the wood grain. Environmentally friendly, tung oil hardens well yet remains elastic and flexible, preventing cracks and extending the wood’s lifespan. It is resistant to acids and alcohols.

_Cons_: It may take longer to dry compared to other finishes and has an unpleasant odor until it fully cures.

_Where to Buy It:_
[Eternal Parquet](https://eternalparquet.com/pt-pt/products/estratto-di-olio-di-legno-puro-tung-oil-olio-di-tung)
[Lisbon Store- Restaurar Conservar](http://www.restaurarconservar.com/Oleo-de-Tungue-Puro)
[Amazon](https://www.amazon.com/Hopes-Waterproof-Natural-Finish-Sealer/dp/B002V4PF3K)

- **Shellac**
 
![Screen Shot 2024-08-28 at 3 00 01 PM](https://github.com/user-attachments/assets/655dc06a-5244-4fef-bd5e-dc24a735a36c)

_Features_: Made from a resin secreted by the lac bug, shellac is natural and food-safe when pure (without added chemicals).

_Application_: Apply with a brush or cloth in thin coats. It dries quickly, allowing multiple coats to be applied in a single day.

_Finish_: The color ranges from warm amber to clear, depending on the number of coats applied. Provides a low sheen finish.

_Pros_: Quick drying time. Commonly used to coat sweets, candies, and toys. Performs well in humid environments and doesn’t yellow over time.

_Cons_: It can be sensitive to heat and moisture and requires skill for a smooth finish, as brush strokes may be visible if not applied correctly.

_Where to Buy It:_
[Amazon](https://www.amazon.com/Terlans-Shellac-Antique-Instruments-furnitures/dp/B0C55VDQ8T/ref=sr_1_3?dib=eyJ2IjoiMSJ9.T7wj2cYWwwHn00CX4BKyIEhu4n7Ts-sqd5HZSse0n9foaKD7ezZQlvdI8HVkjY7fzKBLum9F7B66-T0--W7kWJE1Zv5hlZmYmiUo88MGyfJLVWcdrgrv7KAP9wdkQJf2X5kN1DTltLxqU8lloE2NM7Hn0bTeJq8LuRZrd4UpkD0_AlIl-v0wOs_hLy4YR_gkaREBcv7qkxirujw8tqR4v86JGp0vPjFA5zKa0R3xyhLbIXoqbadBbjA-mlSeN5NvD7TMkCWLPstCEpzz4bmcHxwfBoqP9GbV-Pftg7RPCj0.fbA_zEekUYgIeM5XDTNBevjPqnl4hCla9tNPEZ9r5Mk&dib_tag=se&keywords=shellac+wood+finish&qid=1724855568&refinements=p_72%3A1248909011&rnid=1248907011&s=hi&sr=1-3)
[Lisbon- Restaurar Conservar](http://www.restaurarconservar.com/Shellac-Flakes) _these are flakes!_

-  **Beeswax**

![Screen Shot 2024-08-28 at 4 26 18 PM](https://github.com/user-attachments/assets/ec5afc98-a491-4869-98b4-aceff65901c5)

_Features_: Beeswax is non-toxic and food-safe. It gives the wood a soft, lustrous finish while conditioning and protecting it.

_Application_: Rub the wax onto the wood with a soft cloth, then buff it after it soaks in. It's a great option for maintaining the wood’s natural look.

_Finish_: A soft finish that emphasizes the wood's natural texture.

_Pros_: Easy to use and naturally non-toxic. Highly water-resistant.

_Cons_: It hardens quickly and requires frequent reapplications for optimal protection. It is also susceptible to scratches and dings.

_Where to Buy It:_
[Amazon](https://www.amazon.com/s?k=beeswax+for+wood&crid=2D69SKDKB6I4H&sprefix=beeswax+for+wood%2Caps%2C1195&ref=nb_sb_noss_1)
[Lisbon Store- Restaurar Conservar](http://www.restaurarconservar.com/epages/298256.sf/pt_PT/?ObjectID=13726683)

- **Walnut Oil**
 
![Screen Shot 2024-08-28 at 5 01 28 PM](https://github.com/user-attachments/assets/f53a7965-23e3-4750-81e2-010dcb611475)

_Features_: Walnut oil is a food-grade, natural oil that provides a durable finish and enhances the wood grain. Unlike some other oils, it hardens over time, creating a long-lasting finish.

_Application_: Apply multiple thin coats using a brush or cloth, allowing each coat to dry. It may take longer to dry fully but provides a rich, warm finish.

_Finish_: A clear-satin finish.

_Pros_: Moisture-resistant and durable. It enhances the wood grain.

_Cons_: Long drying time and requires maintenance.

_Where to Buy It:_
[Amazon](https://www.amazon.com/s?k=walnut+oil+for+wood&rh=n%3A3760901%2Cp_72%3A1248903011&dc&ds=v1%3AAW523P9esu%2B8YtaEmUS0SEeYeuL917SYAxtkht35oP0&crid=3BXT7WTWW5HOX&qid=1724859142&rnid=1248901011&sprefix=walnut+oil%2Caps%2C191&ref=sr_rib_d_web_fi_0_0_a_1248903011_0)
[Lisbon Store- Restaurar Conservar](http://www.restaurarconservar.com/epages/298256.sf/pt_PT/?ObjectPath=/Shops/298256/Products/Oil)

Alternatively, we could also mix [Carnauba Wax](https://www.turtlewax.com/blogs/how-to/what-is-carnauba-wax-and-how-should-you-use-it) and [Mineral Oil](https://www.homedit.com/mineral-oil-for-wood/) to make the wood more water-resistant and polished.

References:
https://thetoolsquare.com/food-safe-wood-finish/
https://resin-expert.com/en/guide/food-safe-wood-finish
https://woodsmithspirit.com/food-safe-wood-finishes/

Thoughts? :)

**Comment by nelsonic** [comment]
We have linseed (`IKEA` = foodsafe) oil in the workshop next to the paint tins. 
We apply it with a paper towel. 
can show you this later after my work. 👌

**Comment by KrishaD20** [comment]
@nelsonic Linseed is also a good choice! :)
