### ISSUE TITLE
Upstairs (daylight!) Desk? 💻 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#290]
I’d like to have a desk where I can sit to work when there isn’t anyone in the dining room:

![IMG_7544](https://github.com/user-attachments/assets/314a7968-3b10-480e-b339-3c47d526f4f5)

I will make a sign for what times of day it can be used.

**Comment by nelsonic** [comment]
Really like the IKEA bamboo desk:
https://www.olx.pt/d/anuncio/mesa-para-estudo-do-ikea-IDI0XOU.html

![IMG_7553](https://github.com/user-attachments/assets/b0436ab9-24e4-4772-8e11-5396ae7800dd)
![IMG_7554](https://github.com/user-attachments/assets/04b2f9fa-ad13-4407-8387-7c3f99f8dead)

**Comment by iteles** [comment]
I onde ring if maybe we could please use the perfectly good (great!) desk that's in the library for now?
It makes the library harder to use and is just a dumping ground for things. I can get it cleared tomorrow if we can use this even as just a trial desk for now?

**Comment by nelsonic** [comment]
Clearing the library desk is a great *separate* task. 👌

**Comment by nelsonic** [comment]
Meanwhile it's been 2 weeks and  I'm still working in the basement for no reason ... ⏳ 🤷‍♂️ 
`while` there is **glorious _natural_ light** in the dining room. ☀️ 

![image](https://github.com/user-attachments/assets/951ef6c3-6ea9-463b-961e-e79b74c6d145)
![image](https://github.com/user-attachments/assets/70023c14-e4ae-4bcf-b08a-351ad3377862)

It makes sense to work in the basement when I need to be close to the workshop. 🛠️ 
But for **`work-work`** what I need is some natural light to not go crazy. 🥴

The desk in the library is still cluttered; we definitely have "too many books" ... 📚 again, _separate_ issue: #291

**Comment by nelsonic** [comment]
For context, this desk costs **`€165`** from `IKEA` if we were to buy it `New` 🆕 💰 
https://www.ikea.com/pt/en/p/anfallare-hilver-desk-bamboo-s29417710/

<img width="1245" alt="image" src="https://github.com/user-attachments/assets/75a938c4-1758-4b9c-a38f-5e52c76236b4">

> For ref: I think that's daylight robbery for a `static` desk! 🤯 

The **`ANFALLARE`** bamboo Table top _alone_ is **`€85`**:
https://www.ikea.com/pt/en/p/anfallare-table-top-bamboo-00465141/
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/74fb684f-8a78-469c-bf60-3b3c33fe5d30">

The **`HILVER`** legs, `while` well-designed are _extortionate_ at **`€20/each`**!!
https://www.ikea.com/pt/pt/p/hilver-perna-conica-bambu-80278273/
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/c8ed2372-adac-4d43-826d-9f34cf579664">

But **`€65`** for the desk:
https://www.olx.pt/d/anuncio/secretaeia-de-escritrio-ikea-anfallare-com-arrumacao-de-cabos-IDIa8ve.html?reason=observed_ad
<img width="1321" alt="image" src="https://github.com/user-attachments/assets/cf7456b3-5f6f-4753-8de4-3da93e57e2ca">

Including the **`SIGNUM`** under-desk Cable trunking which costs **`€12,99`**:
https://www.ikea.com/pt/en/p/signum-cable-trunking-horizontal-silver-colour-30200253/
<img width="1245" alt="image" src="https://github.com/user-attachments/assets/cfba8b6c-0b90-4851-9bcf-36a765f9c77b">

Is a _muuuch_ more attractive offer! 😍 
Even if it requires a **`T1h`** (after work) round-trip to collect it. ⏳ = 💸

**Comment by nelsonic** [comment]
Zero Regrets buying Bamboo Desks and moving to the light-filled room. ☀️ 
Won't be permanent. But at least until we open to guests this is a good spot. 🧑‍💻
