### ISSUE TITLE
Moving No Longer/Infrequently Used Kids Items

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#295]
These items have been in the dining room corner for too long:
<img width="911" alt="image" src="https://github.com/user-attachments/assets/18a6a6d1-bdbd-4d7c-81fc-19aa890da6c5">

@iteles where do they *belong*? 🙏

> they feel abandoned and they are always in my photos when I trie to capture something in the dining room. 😢

**Comment by nelsonic** [comment]
Items ***temporarily*** moved to the alcove of the urinou which is ***not*** currently being used:

![IMG_9531](https://github.com/user-attachments/assets/019c0d85-2641-4d77-9f1f-7437837c15fb)

Area cleaned:
![IMG_9535](https://github.com/user-attachments/assets/07f01684-a58b-478e-a478-f5d7fef15a3a)

**Comment by iteles** [comment]
They are listed for sale and I optimistically left them there so I wouldn't have to keep running up to the attic for things. So I guess now I can just find a corner in the attic for them (aside from the spare highchair which I think it makes total sense to keep in the dining room 🤷‍♀️ ).

**Comment by nelsonic** [comment]
Dining room is the most "nice place to be" room in the house. Definitely not a "storage room" ...
The "spare" highchair is only used by us at other people's houses ~monthly so should be stored out-of-sight.

**Comment by nelsonic** [comment]
Closing as you are aware that I have moved the items and where they are. ✅
