### ISSUE TITLE
Shower Leaking into Kitchen 🚿 💧😢

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#297]
![IMG_9832](https://github.com/user-attachments/assets/5a4ceb88-4990-4948-9957-e0b8ecdf82e7)

https://github.com/user-attachments/assets/807b36c1-38fc-4455-be09-5905c5cca6e6

@iteles this leak is directly below the shower you use. 🚿
Assigning to you so you can triage and  investigate. 🕵️‍♀️  
might want to call Carlos for this one. 😬

> Addendum: my biggest concern with this is how close the leak is to the _light_ 💡 (see photo above)
> If this was to short-circuit the lights it could be an _even_ bigger problem. 😬

**Comment by iteles** [comment]
Carlos Pinheiro? Because of the ceiling portion of the leak?
I don't think he'll have much/any availability 🙃 

Our ceiling will always look patched, I'm assuming. 

We need to determine how to open up the ceiling before we get the plumbers out.

**Comment by nelsonic** [comment]
I don't expect Carlos Pinheiro to have "availability" ...
But he was _here_ when all the plumbing was done by the original team.
So he will be able to _help_ us diagnose the problem ...

The ceiling will look like _new_ provided we get a _competent_ person to do the patch work. 
See: "How to fix holes in drywall": https://youtu.be/uvQK7WTkKpI
The obvious _challenge/difficulty_ is it being overhead ...
But there are plenty of online tutorials/videos so ***you*** can be knowledgeable on this topic
when delegating/supervising the repair task.

The ceiling can be opened with a Stanley/Art knife. It needs to be done strategically with the repair in mind.

**Comment by iteles** [comment]
Pinheiro says we have about 25cm of teto falso and we should open a small hole to check where the bigger hole needs to be opened. He also confirmed that opening a 20cm hole or a 1m hole was much of a muchness as the repair is 'an easy fix'.

I've spoken to Palhagua the plumbers who are flat out on obras far away and will call me back to confirm if there is any chance they could spare someone for a day this week.

**Comment by nelsonic** [comment]
We can slice open the roof ourselves (this evening after work) 🔪 
or we can axsk Miguel to do it tomorrow morning. 💭 
IMO there's zero urgency to rip a hole in our roof and have our kids _constantly_ pointing it out to us ... 🕳️ ☝️ 🙃 
But we _do_ need to get it done at some point to assess the damage. 😬

**Comment by iteles** [comment]
Exactly. I wouldn't do it until we have the plumber dates 👌🏻

**Comment by iteles** [comment]
The plumber came out and figured out that the shower base had come away from the wall, coupled with the water getting in behind the tap plates on the shower wall itself.

We quickly had him reseal the shower base and all the plates for €150 but I'm SO angry at myself. 
All of the shower plates on the wall will need to be pulled off because we still haven't resolved the issue where the shower safety clip needs to be removed. I'll open a separate issue on that.

**Comment by nelsonic** [comment]
@iteles please confirm `if` you're happy with the fix. 👌 (close this issue ...)

**Comment by iteles** [comment]
Confirmed!
