### ISSUE TITLE
Middle floor W/C light not working 💡😢

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#307]
Light doesn’t turn on:
![IMG_2923](https://github.com/user-attachments/assets/5607de7b-6705-43ae-b0e7-b6a1da4abca0)

Other lights on the same circuit are working g fine. So I think it’s the LED. 😢
Sadly, that requires a complete replacement.
@iteles do you want to pick a simpler light? 💡

**Comment by iteles** [comment]
Could also be sensor issue and not a LED issue?

**Comment by nelsonic** [comment]
The sensor appears to trigger and the light is _very_ dim.
But I will just replace _both_ the sensor and the light. 

@iteles would you like to select the replacement light?
***or*** are you happy for me to select one (similar to the current one) and just crack on?

**Comment by iteles** [comment]
A similar one (the plainest possible) will be great next time you're at LM

**Comment by nelsonic** [comment]
Removed the diffuser on the light and you can see there are a few LEDs that still light up but dimly:

![IMG_3135](https://github.com/user-attachments/assets/e0afc0a4-8bff-43b8-8f9b-44bdb28ced2b)

So we know it’s not the IR sensor that has failed. (As I suspected because it still triggers - making the clicking sound - when we walk in…)

So I’ve completely removed the light from the ceiling:

![IMG_3136](https://github.com/user-attachments/assets/ab54d8b7-f833-4e02-ab22-986d79e9ed1a)
![IMG_3140](https://github.com/user-attachments/assets/48454765-5a6b-4576-8d44-117bcc5ce65e)

And will be taking it with me now to Leroy as I’m buying a few other items.

**Comment by nelsonic** [comment]
Spent time with the sales assistant in Leroy finding a light that matches the holes we already have in the ceiling I.e. same config as the previous light. 💡 

This is the only one they have in-stock:

![IMG_3142](https://github.com/user-attachments/assets/e31945b3-4c22-448f-8205-7a66d793efcc)

Not cheap, but saves us time on installing and is very bright which we need for the w/c. 

@iteles we also spent 15 mins digging through receipts in the App/PC looking for when the broken light was purchased, no luck. If we had found it, the 5 year warranty would have meant we would get a voucher for the value. 

Is it worth buying this new light without the company NIF so we get the full 5 years of warranty again? 💡⏳💭

**Comment by iteles** [comment]
Yes to buying and for that price, yes to no NIF.

**Comment by nelsonic** [comment]
Ok, will still put it on your Leroy account in case we need to find the receipt in 4 years time to get a refund. Just not the company NIF. 👌

**Comment by nelsonic** [comment]
![IMG_3150](https://github.com/user-attachments/assets/f72c620b-5c7f-43db-ba7d-53188b5aaf9b)

Purchase associate with your store card/account. 
will install when I get back. 🤞🏼💡

**Comment by nelsonic** [comment]
Replaced, all working. Much brighter than the previous one which is really good! 

![IMG_3165](https://github.com/user-attachments/assets/9c03de5b-6b2b-46a2-9133-48c5815eb7f0)

Remote control has batteries in it (not included in packaging…) so you can adjust brightness and color temp if you want:

![IMG_3166](https://github.com/user-attachments/assets/20061582-228a-4e10-af4a-4ae05a344312)

Labeled so it won’t go missing.
dated so we can lookup this receipt if we ever need to.
Remote lives on top shelf of coat rack next to first aid cabinet key:

![IMG_3167](https://github.com/user-attachments/assets/528c2636-b38a-429e-8191-a72bf931490b)

Closing as complete. 💡✅
Feedback always welcome. 🙏

**Comment by iteles** [comment]
Looks awesome, actually prefer this light to the previous one (which we bought in the summer of 2019 and was just out of warranty). Thanks for sorting.
