### ISSUE TITLE
Idea for mesh internet network

### ISSUE THREAD

**Issue by 2color** [dwyl/home#33]
I thought you might find this interesting. 

https://althea.org/

**Comment by nelsonic** [comment]
@2color thanks for sharing! this looks _very_ much like something that will interest us. 👍 
![image](https://user-images.githubusercontent.com/194400/51231220-ab1bfd00-195a-11e9-976d-4e719c5d6af8.png)
![image](https://user-images.githubusercontent.com/194400/51231249-bff89080-195a-11e9-8e57-efc1c1be6b06.png)
![image](https://user-images.githubusercontent.com/194400/51231257-c555db00-195a-11e9-89ab-45ae72882720.png)
![image](https://user-images.githubusercontent.com/194400/51231276-d272ca00-195a-11e9-87ac-3962221931fa.png)

Definitely worth an investigation: https://github.com/althea-mesh 🔍

**Comment by nelsonic** [comment]
https://eero.com/
![image](https://user-images.githubusercontent.com/194400/52737834-2eb22380-2fc5-11e9-9208-23ad1775bbc9.png)

[![image](https://user-images.githubusercontent.com/194400/52737992-91a3ba80-2fc5-11e9-8a32-200311ba07c8.png)](https://youtu.be/5-nozZmtG38)
https://youtu.be/5-nozZmtG38

[![image](https://user-images.githubusercontent.com/194400/52737736-f90d3a80-2fc4-11e9-91b1-321445353550.png)](https://youtu.be/qhzAuYz0SPs)
https://youtu.be/qhzAuYz0SPs

https://www.businesswire.com/news/home/20190211005750/en/Amazon-Acquire-eero-Customers-Connect-Smart-Home
