### ISSUE TITLE
Visiting YC in Mountain View, CA

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#4]
@iteles given that you/we have been `#accepted` to be in Startup School 2018! 🎉 
what are your thoughts on going out to California for a Week in October (_the week after Hamburg_)
to meet/visit the YC peeps and visit other co-living/co-working spaces e.g RGB house #3 

I would organise _everything_ including flights, connections, accommodation and "activities" ...
(_similar to the last time you went to US to visit me while I was still working for Groupon..._)

**Comment by iteles** [comment]
This sounds epic! We need to review our full timeline for Braga (including bank loan and launch) this weekend to determine feasibility 👍

**Comment by nelsonic** [comment]
Sadly, this is not going to happen. We have "too much on", need to focus 
on getting the house open and cannot afford to spend 1 week of time in California ...
I think if we had a _clear_ [shared] goal on the _software_ side it would be _logical_ to visit YC! ✈️ 🌎 🤓 
But given that there hasn't been any comment/engagement with https://github.com/dwyl/product-roadmap/issues/7 (_emoji "reactions" do **not `count`** because they are not **timestamped**_) 
I feel that _closing_ this issue is the _logical_ action. ✅
