### ISSUE TITLE
Hatch door for outdoor machine room

### ISSUE THREAD

**Issue by iteles** [dwyl/home#43]
Sub-issue of https://github.com/ideaq/home/issues/16#issuecomment-462719890 (Sauna)
![image](https://user-images.githubusercontent.com/4185328/52633304-d93e1f80-2ebb-11e9-9c34-a25b449f3cdc.png)
![image](https://user-images.githubusercontent.com/4185328/52633333-e955ff00-2ebb-11e9-83d6-165e1bdf6459.png)

**Comment by iteles** [comment]
@nelsonic The largest machine to fit through the door is 750mm at its widest point.

**Comment by nelsonic** [comment]
@iteles **750mm** _assumes_ that the machine will pass through independently (_i.e. with out a person's arm_) and unobstructed by the stairs ... that might be the case when it's _first_ installed, but when _maintenance_ or a future _upgrade_ is required, manoeuvrability/accessibility to the room will be _essential_. 



Given that we are going to _custom_ make the door based on our _exact_ specifications, I would actually make it _bigger_ e.g: 1200mm x 1200mm such that we could fit an IBC through the opening.
But on the basis that that would be "too much future proofing" I say we _stick_ with the plan of **1000mm x 1000mm** to _avoid_ ***any*** "_confusion_" with the workmen and "changes of plan" causing any _delays_.

**Comment by iteles** [comment]
Thanks @nelsonic. I have confirmed with the workmen that this will in fact remain as per the original plans.

**Comment by nelsonic** [comment]
@iteles thanks. :shipit:

**Comment by nelsonic** [comment]
Derp! "Close and comment" indeed. 🙄

**Comment by iteles** [comment]
The hole has been left and now this is with us to buy/commission the hatch door so that the machines can be installed.

**Comment by iteles** [comment]
Measuring the hole on Monday so that we can commission the trap door.

I've already emailed the metal worker to give him a heads up this will likely be coming his way and confirm it's something he does.

**Comment by nelsonic** [comment]
Got the measurements today:
Width: 970mm
Length: 1170mm

@iteles let me know when you have time to pair on requesting the quote for the door.
Thanks! ☀️

**Comment by iteles** [comment]
Spoke to the metalworkers yesterday and they asked to come to the house on Monday to determine what we needed.

**Comment by nelsonic** [comment]
@iteles any update from the metalworker? ⏳ (_should we be considering an alt supplier...?_) 💭

**Comment by iteles** [comment]
I've been calling him 2 times a week for 4 weeks. He called me on Saturday to say he'd send me a quote and could get the work done _this week_.

But I'll believe it when I see it ⏳

**Comment by iteles** [comment]
![cf1bf5e7-a56c-43ae-b36f-f8f101c2bfd9](https://user-images.githubusercontent.com/4185328/60612067-c327f180-9dbf-11e9-8a5e-18ee89582011.jpg)
![dc05dfde-e261-4231-9bcf-7df71877bdc3](https://user-images.githubusercontent.com/4185328/60612071-c4f1b500-9dbf-11e9-9870-6ef19c9ab5f5.jpg)

**Comment by nelsonic** [comment]
@iteles you should see what it looks like after being pelted by a storm if rocks... 🙄

**Comment by iteles** [comment]
OH NO! 😭

**Comment by iteles** [comment]
@nelsonic Did you get the key to this that was supposedly left in the post box when it was installed?

Also, Carlos was saying that we'd need to cut ventilation holes into it for the machines which makes a certain amount of sense but.... 🙄 One to review with Sr. Pinheiro

**Comment by nelsonic** [comment]
@iteles keys are stored safely. 👍 
We need to understand what the ventilation situation is on Monday. 📆

**Comment by iteles** [comment]
Ventilation will be done separately to the hatch door so closing this for now.
