### ISSUE TITLE
Step down power supplies for the doors

### ISSUE THREAD

**Issue by iteles** [dwyl/home#46]
Following on from: https://github.com/dwyl/home/issues/34#issuecomment-460689808
![image](https://user-images.githubusercontent.com/4185328/52918608-eb232680-32f0-11e9-9224-08086f40f882.png)

We had a conversation with the electricians on-site and spoke about buying a step down power supply to test with the doors and so that the electricians can bring a sample electrical box to try at the house 👍

**Comment by iteles** [comment]
Doors should be ready to start being installed in the bathrooms and machine room on Tuesday with the other room doors available from Wednesday! 🎉

**Comment by nelsonic** [comment]
Hopefully this will not be required as I intend to power the doors from the PoE Switch. 💡
