### ISSUE TITLE
Bathroom sinks

### ISSUE THREAD

**Issue by iteles** [dwyl/home#65]
We need 2 double sinks and 2 single sinks for the non-reduced mobility bathrooms.

We've been to a few different locations to look at sinks but the best quality for now still appear to be Ikea. 

For example, the Leroy Merlin display models look pretty worn:
![image](https://user-images.githubusercontent.com/4185328/56612786-1ab22000-660d-11e9-969e-58d7b7484a2b.png)

Having been to Ikea, the top proposals and the GODMORGON/ODENSVIK combinations in simple white (not shiny). The basins themselves could stand to be bigger, but this is not the end of the world; I'd prefer to have slightly smaller basins and have a place next to it to place my washbag than the other way around.

i.e. Given that everyone staying at `home` will likely have a couple of things they bring to the bathroom with them, the Ikea options below with space around them are better than this one for example (although it's very pretty!):   
![image](https://user-images.githubusercontent.com/4185328/56614015-d83e1280-660f-11e9-80b3-80e391cc35d3.png)
 

The key question is the **width of the wash-stand**. At the time we had the fittings/plumbing installed for the sinks in the bathrooms, we estimated they  would be around 120cm wide for the doubles and 80 or 90cm wide for  the singles.

## Double basins

Whilst I like the _look_ of the double basins with 2 wide drawers:
[![image](https://user-images.githubusercontent.com/4185328/56613108-e2f7a800-660d-11e9-9c6e-26139ebe1ef9.png)](https://www.ikea.com/pt/pt/catalog/products/S09185462/#/S19185225)

I think the additional space (though not much) of the 4 drawer wash-stands would be useful _and_ are more in keeping with the :

[![image](https://user-images.githubusercontent.com/4185328/56613273-336f0580-660e-11e9-9b77-e5b53242aff7.png)](https://www.ikea.com/pt/pt/catalog/products/S09186027/#/S69185237)

## Single basins
For the sink in the basement I don't think there's any doubt here, we're size constrained.
The mirror below is 60cm wide:

![IMG_0983](https://user-images.githubusercontent.com/4185328/56614333-b6915b00-6610-11e9-9fb6-d4a2ad1213c4.JPG)

So the only option is this size of wash-stand:
[![image](https://user-images.githubusercontent.com/4185328/56613825-62d24200-660f-11e9-90cd-220b132c2dea.png)](https://www.ikea.com/pt/pt/catalog/products/S59023504/)

#### But for the _middle_ floor bathroom, we have more space to play with so I'm thinking:
[![image](https://user-images.githubusercontent.com/4185328/56614591-3fa89200-6611-11e9-9241-c5a200b2ba9f.png)](https://www.ikea.com/pt/pt/catalog/products/S59023504/)

_or even this_ if the plumbing allows:
[![image](https://user-images.githubusercontent.com/4185328/56614659-6f579a00-6611-11e9-8a82-3ff97da39d6b.png)](https://www.ikea.com/pt/pt/catalog/products/S69185242/)

**Comment by iteles** [comment]
For the middle floor bathroom, this is what the plumbing situation looks like:
![20190424_112708](https://user-images.githubusercontent.com/4185328/56653037-b03cc680-6684-11e9-8a8a-51c02689eb4c.jpg)

The mirror is up against the wall (don't let the optical illusion of it reflecting back tiles fool you) and is 120cm wide.

This means that if we went for the 123cm wide option (with 4 drawers), it would stick out 3-5cm to the right of the mirror. The alternative is the two drawer, 103cm wide wash-stand, but then that gives us a bit less space.

The question is, **would having it stick out drive people crazy**? 😬

**Comment by nelsonic** [comment]
@iteles 3cm overhang won't be a problem.

**Comment by nelsonic** [comment]
@iteles do we have a record of when it was decided that the sink in the middle floor would be a _single_ as opposed to double?

**Comment by iteles** [comment]
@nelsonic You, my friend, are right.

The plans have always included a double basin here:
![image](https://user-images.githubusercontent.com/4185328/56669797-9bbef500-66a9-11e9-818f-f8bc7a26669e.png)

However, the plumbing seems to have been carried out for only one basin and I honestly didn't think to check until now.

The advantage of having _one_ basin is that there won't be anyone standing super close to the opening door of the toilet and it's unlikely 2 people will _need_ to wash their hands at once.
Having two _would_ be better than one but I don't think it would be worth ripping things up to get it done now.

I have emailed the plumbers to check if the intention is that this will somehow be enough for 2 basins (but I doubt it because there looks to be only one electrical supply).

**Comment by nelsonic** [comment]
@iteles we don't _need_ to "rip" anything up in order to have 2 basins and the dimensions of the 2-basin unit is essentially the same as the 1-basin unit. The only major difference is the cost of the Taps. 💸

**Comment by iteles** [comment]
Just want to double-check with the plumbers and electricians that with the existing plumbing and electrical installation we _can_ have two basins (as in the upstairs bathrooms where we _definitely_ have double basins there are two sets of plumbing and electrical installations whereas here we only have one).

We won't get a reply now until Friday given tomorrow is a bank holiday in Portugal.

In the meantime, I can confirm we ordered 6 taps and not 7 so we _would_ need to buy an extra tap, which you're right, are super expensive 😞 

How likely is it that more than one person will be using the bathroom taps? Half of the work space will be nearer to the kitchen anyway....

**Comment by nelsonic** [comment]
@iteles I _agree_ that the likelihood of two people needing to wash their hands concurrently is _low_. 
And the _most_ anyone would have to wait is 30 seconds ... ⏳ 

I think what _sways_ me towards a single sink (_besides the cost of the high quality sensor tap, approx €300_) is the fact that it's more to clean and maintain on an ongoing basis 
(_i.e. more work for the housekeeper... with limited benefit ..._)

**Comment by iteles** [comment]
Single sink it is! And I'm thinking of going for the 4 drawer, 123cm for everything except the basement bathrooms. Will get on with purchasing this today!

**Comment by nelsonic** [comment]
@iteles what are you going to _store_ in the drawers? 
(_all "spare" soaps and TP will be stored in the **locked** pantry to avoid any disappearing acts..._)

**Comment by iteles** [comment]
For the female bathroom upstairs at least, I had envisioned having a bit more space so that depending on the number of women half-drawer boxes (like the below) so that each person could keep _some_ of their everyday things in the numbered boxes, rather than lugging everything back and forth to their rooms.

This kind of thing: small but enough to keep shampoos and bath gels standing upright.

![image](https://user-images.githubusercontent.com/4185328/58589354-94b37580-8259-11e9-8f18-03c51b801e00.png)

**Comment by nelsonic** [comment]
@iteles I am happy to _test_ this idea.

My hypothesis is that it is a _good_ idea in _principal_ but won't be practical for clutter/chaos and  **`WHEN`** things go missing (_because someone borrows something..._) it will create instant animosity. 😞 
Having lived in a Hostel for long enough, I know that the single biggest constraint is secure _personal_  storage space and there is almost _zero_ communal storage space except for the kitchens which are usually chaos. 

The design for the bunk beds will contain _plenty_ of easily accessible personal storage space for even the most lotions+potions of people. The biggest advantage of storing _everything_ in either the bunk or the kitchen is that it's less clutter/mess and chance for things to go missing.

But if you think you can create a _system_ for bathroom storage that people will adhere to, go for it!

**Comment by iteles** [comment]
Smaller ones it is 👍

**Comment by iteles** [comment]
@nelsonic We ordered the sinks at the shop physically on Monday to try to get them sooner but I'm on the verge of freaking out with Ikea.

First they were going to be delivered on 5-Jun, then 7-Jun, then someone was hurt on their team and they rescheduled to Saturday 8-Jun and now I've received a phone call apologising _again_ but they can now only do Tuesday 11-Jun because of a new scheduling issue with the bank holiday they hadn't accounted for. 😕

**Comment by iteles** [comment]
![4241d143-a2c6-4637-81d5-f44f636b1faf](https://user-images.githubusercontent.com/4185328/59696140-59b2bb00-91e3-11e9-83fd-0579371309e0.jpg)
![0c99aae8-e337-4aaf-9056-30714e4fc785](https://user-images.githubusercontent.com/4185328/59696143-5ae3e800-91e3-11e9-854d-fe7cb0181f20.jpg)
![IMG_1159](https://user-images.githubusercontent.com/4185328/59696146-5b7c7e80-91e3-11e9-956e-3ebae56484f1.JPG)
![IMG_1162](https://user-images.githubusercontent.com/4185328/59696570-2ae91480-91e4-11e9-98ee-c1a57923648b.JPG)
