### ISSUE TITLE
Updating the electrical wiring location for the upstairs floor

### ISSUE THREAD

**Issue by iteles** [dwyl/home#69]
Having reviewed everything with the engineer yesterday to ensure we didn't have any surprises when we asked for our electrical certification, we discovered that the electrical wiring for the bedrooms on the upstairs floor had been directed to the main switchboard rather than the dedicated one on the upstairs floor itself.

This has to be redirected.
In order to do this, we have to lift the floorboards in that section to pick up the electrical wiring from the landing of the upstairs floor.

***The problem as our builder has explained it to me is that in order to lift the floorboards given how he's laid the flooring, he has to lift the whole room's flooring as well as just that corridor section.** He knows this because when he fixed the section that got soaked with a bucket of water, he found he had to lift the whole of the room in order for this to come out. 😭 

### Option 1
Cut the floor boards at the entrance to the Southern corner room and **put a piece of wood across the floor of the doorway**, a 'baguette'.   
You wouldn't notice it if the door is closed but you'd step over it if you opened the door.

### Option 2
Lift up the floorboards in the entire room and lay everything again so that it goes down without a join at the doorway.

**Comment by nelsonic** [comment]
@iteles if Carlos doesn't have availability to do the work of lifting the floorboards and replacing them then Pedro must find us a day labourer who we can pay to do it. The buck stops with Pedro he was hired with the ***one job***: to ensure the other tradesmen did their job properly! They have all been _generously_ compensated and we are not demanding anything extraordinary, just "do it right the first time". 

For future reference, when something has been done _wrong_, there is only _one_ "option": Make it _right_. 
(_i.e. **don't cut corners** to save a few hours of work!!_)
If Carlos or Pedro do not have anyone to do the work _right_ I will do it myself!

**Comment by iteles** [comment]
I agree and called him back to confirm this before removing the `question` label. 

Thank you for writing up my reasoning for me. In addition to this, I would also add that having a 'patch' here is like a gateway drug to more compromises and patches.

No matter how much of a pain it is for Carlos, I've confirmed with him that it's a priority and will need to be done in order to set the right tone in the house.

**Comment by iteles** [comment]
This is now complete.
