### ISSUE TITLE
Startup School Weekly Updates

### ISSUE THREAD

**Issue by iteles** [dwyl/home#7]
For the first group 'office hours' call, we need to have the following ready:
+ Company 1-liner to remind everyone what you do
+ How far along are you / quick summary of status of company
+ Goals for next week
+ Biggest obstacle/problem that the group can help you with
+ What you hope to get out of Startup School

I will write a starting point for discussion.

**Comment by iteles** [comment]
Very first draft for discussion.

### Company 1-liner
'home' is a data-driven, co-living and co-working space for digital nomads and founders with a focus on healthy living and good habit formation.

(Quite wordy and not punchy enough. I feel like it needs to be infused with more of our enthusiasm and values!)

### How far along are you?
We've been thinking about `home` for a long time!
`home` is _technically_ at the concept/idea stage but we are quite far along in the bricks & mortar portion of it. We have (in broad strokes):
+ Found & bought a property (bootstrapped)
+ Worked through and designed all the changes to the property necessary
+ Started construction work (5 months and 70% complete)
+ Begun the interior design 

For the concept itself we have:
+ Discussed it at length and written a high level plan
+ Created initial financial plans (revised multiple times already in light of construction)
+ Discussed the application that will form the technical and remote heart of `home`

### Goals for next week
+ Determine the feasible MVP for launch at the end of startup school 
+ Set out the planned steps needed to achieve this

### Biggest obstacle/problem that the group can help you with
+ Has anyone had experience of measurement of happiness/communities that worked extremely well?

### Goal for Startup School
Launching the MVP of our application and having a full plan in place for opening the space itself once construction is complete!

### What you hope to get out of Startup School
A fantastic community, a structure with which to drive everything forward!

**Comment by nelsonic** [comment]
This week we have been:
1. Writing code for our MVP app, we expect to have a "quantum of utility" by next week.
2. Managing the building works/project.
3. Reviewing our financial data and comparing actual costs to our original estimates.

Our biggest "challenge" is knowing how much/little is required in order to launch the app!
but we think we have the essential features/requirements captured, we just need to keep our heads down and write the code.

**Comment by iteles** [comment]
Yes! 👍 

During the update I added:
+ **Goals for next week**: Nailing down the rest of the construction schedule (so we can at least move into one room)
+ Noted the difficulty of managing urgent vs important when even though the app is more pressing, if the house build is delayed, all our contractors will disappear for 8 months to their next jobs.

**Comment by iteles** [comment]
## Week 5 update

### This week:
+ Physical world: construction began again, carpenter is making the most progress and we have a dependency on the main builder before electricians and plumbers
+ App: User testing & set requirements. Built foundation modules to enable building next phase of the application.

### Goals for next week:
+ Physical world: unblock other specialties by getting main builder started again, pick 3 decisions we need to make that ensure no one in blocked in 2 weeks time
+ App: Build next set of functionality so it can be user tested the following week.

**Comment by iteles** [comment]
## Week 6 update

### This week:
+ First coat of paint in the interior of the house!
+ Went round the house with every specialty and worked out the plan and dependencies
+ Sent builders all plans for the final parts that still need to be estimated
+ Recruited intern/apprentice
+ Interesting note: mentioned in a comment on HN and went from 5 stars to 74 stars in the repo in half a day (this is without doubt a vanity metric), but seeing as we haven't really spoken publicly about it yet, it's nice for morale that people are interested in following the journey!

### Goals for next week:
+ Finalise bank loan
+ Push builders to stick to timelines to ensure progress!
+ Plan and start simple MVP website to get something out there

### Anything the group can help with?
+ Name! It's not the most important thing, but I'd like to put some thought into it
 + I like names with a little story behind them!

**Comment by iteles** [comment]
Feedback from group:
+ Don't spend a huge amount of time on a name because the positioning and brand around it is more important than the name itself
  + Rob Shedd shared http://firstround.com/review/Positioning-Your-Startup-is-Vital-Heres-How-to-Do-It-Right/
+ Thanks to Michael from Pantherion Brands shared:
  + http://www.bustaname.com/
  + https://leandomainsearch.com/

**Comment by iteles** [comment]
@nelsonic Do you want to do the update this week? It's your second to last chance and it would be great for everyone to hear from you!

**Comment by iteles** [comment]
## Week 9 update

### This week:
+ Air inlet issue resolved #21 
+ Started off attic conversion conversations
+ Determined product roadmap until the end of the year

## Goals this week:
+ Finally order final emergency doors for the house (still waiting on the final budgets)
+ Re-prioritise goals for life and ensure we're still on the same page as co-founders now we're reaching the end of startup school
+ Continue to build app
+ Define information architecture for website

**Comment by iteles** [comment]
# Final Week update
Doors finally agreed & ordered which were our largest security blocker for all the other construction in the house and we're also in the process of getting our electricity capacity more than doubled to handle all the tech (that's been a bureaucracy nightmare for a change!). 
The focus this week for the app was on hardware more than anything else, working through all that is needed for the door/app interaction.

**Comment by iteles** [comment]
Startup School has now concluded, this issue can be closed.
