### ISSUE TITLE
Kitchen Fridge

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#80]
This might not seem lie a "big" decision or a particularly important one but look a little deeper ...
In most houses fridges are the electrical appliance with the _most_ daily interactions.

A survey conducted by AppliancesDirect.co.uk showed that Brits look in the fridge **14 times** a day
https://www.housebeautiful.com/uk/lifestyle/storage/news/a2110/fridge-food-cupboard-habits/

# Buying Criteria

+ [x] Fridge capacity > the taler the better
+ [x] Energy Efficiency > A+++
+ [x] Ease of maintenance/cleaning > Stainless Steel
+ [x] Durability of Handles > Concealed handles 

if we assume 20 people open the fridge 10 times per day the handles and hinges will take a _beating_ so the handle must be _integrated_ into the door not a separate. 
An external will be a pain to clean and break quite fast with 200+ opens per day:
![image](https://user-images.githubusercontent.com/194400/60212114-5c9f5280-9858-11e9-9666-9bdad9df523a.png)

A _Concealed_ handle means there is no _yanking_ on the handle and there's less to clean.
![image](https://user-images.githubusercontent.com/194400/60212452-3332f680-9859-11e9-8f7d-7f70e732ee63.png)

# Search 

A great place to find _specific_ kitchen appliances is John Lewis [https://www.johnlewis.com](https://www.johnlewis.com/browse/electricals/fridges-freezers/fridge-freezers/201cm-to-220cm/a+++/_/N-adsZ1z0mqobZ1z0svjn?sortBy=priceLow) 
because their site allows you to filter/search by dimensions like _height_, width and depth:
https://www.johnlewis.com/browse/electricals/fridges-freezers/fridge-freezers/201cm-to-220cm/_/N-adsZ1z0mqob

![image](https://user-images.githubusercontent.com/194400/60206855-7c307e00-984c-11e9-92da-038b2cb0ac83.png)
And energy rating:
![image](https://user-images.githubusercontent.com/194400/60206955-ba2da200-984c-11e9-9607-41a0cd82053c.png)

The _reason_ we want a _taller_ fridge is to get the _most_ capacity for the available floor area.

https://www.johnlewis.com/samsung-rb37j5230sl-freestanding-fridge-freezer-a-energy-rating-60cm-wide-stainless-steel/p1953496
![image](https://user-images.githubusercontent.com/194400/60211474-fe25a480-9856-11e9-809c-6cb7487d23aa.png)

The **Samsung RB37J5230SL** is not available in Portugal (_it appears to be a UK-specific model_)
But the  **Samsung RB37J542VSA** is the PT equivalent and is 59.5 (W) x **201** (H) x 67.5 cm (D) has a total **capacity 353L** (269L fridge + 98L freezer), **A+++** energy rating 
It costs **€659** in Portugal: https://mediamarkt.pt/products/samsung-rb37j542vsa-a-353l-no-frost-frigorifico-combinado-inox 
![image](https://user-images.githubusercontent.com/194400/54635072-504a7300-4a7b-11e9-93d2-9ea668e5602f.png)

Worten Price Check: €665 https://www.worten.pt/grandes-eletrodomesticos/frigorificos/frigorificos-combinados/frigorifico-combinado-samsung-rb37j542vsa-6923641
![image](https://user-images.githubusercontent.com/194400/60212345-f109b500-9858-11e9-8c03-ecea30e1b6cd.png)

## Relevant Reading
+ https://physics.stackexchange.com/questions/349115/is-frequent-opening-of-the-fridge-really-so-significant-for-the-power-consumption

We have previously done _preliminary_ research into fridges as part of designing the [kitchen](https://github.com/dwyl/home/issues/52#issuecomment-474535030) ...
This issue is for consolidating our research and decision criteria for easy reference.

# _Next_ Action

+ [ ] Order _two_ fridges once the kitchen is ready to receive them.

**Comment by iteles** [comment]
@nelsonic The fridge that belongs in the 'alcove' section (in the corridor of the kitchen) can be ordered and installed much sooner than the other two as that portion of the kitchen will only need a lick of paint before it is completed. 

We should take the final measurements and see what is available (noting that a skirting board may make the available area smaller so we'll need to think of how we can 'finish' a skirting board at the wall so that it doesn't go into the alcove itself.

**Comment by nelsonic** [comment]
@iteles the Drinks fridge deserves a _separate_ issue. I _started_ searching for it, but the inclusion of drywall in the "alcove" has really _scuppered_ the idea ... indeed, we need to take the measurements.

**Comment by nelsonic** [comment]
Alcove for "Drinks Fridge" captured in: https://github.com/dwyl/home/issues/82

**Comment by iteles** [comment]
These arrived today! #105
