### ISSUE TITLE
Garage electrical circuit

### ISSUE THREAD

**Issue by iteles** [dwyl/home#87]
It came to light as I was going round with the fire safety inspector and the electricians on Friday that the garage is all on the same electrical circuit with 2.5 wiring.

@nelsonic Carlos has suggested that if you have more than one heavy electricity use there, the circuit might not handle it. Is this something we need to review with the electricians on Tuesday (16-Jul-2019) or something you've already reviewed and are comfortable with?

**Comment by nelsonic** [comment]
@iteles is this still relevant? my understanding is that the electricians have _concluded_ the work in the garage ...

**Comment by iteles** [comment]
The time for this has definitely now passed 👍🏻
