### ISSUE TITLE
The #1 Office Perk? Natural Light

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#9]
https://hbr.org/2018/09/the-1-office-perk-natural-light
via/comments: https://news.ycombinator.com/item?id=17916582
![image](https://user-images.githubusercontent.com/194400/45093615-d3742f00-b110-11e8-951a-ea2bd1edccbe.png)

It's _fairly_ obvious that natural light is a _must_ for **`home`**.
This HRB article offers nothing more than _confirmation_ that people rate it highly in their choice of where to work and _asserts_ that natural light is the biggest single contributor to workplace satisfaction, engagement and effectiveness.

The article mentions "The Spheres" see:
https://blog.aboutamazon.com/sustainability/bringing-the-spheres-green-walls-to-life
![image](https://user-images.githubusercontent.com/194400/45096365-4c2ab980-b118-11e8-9ef3-11981556e9ad.png)

Amazon's "showcase" work environment in Seattle which looks _really_ nice on the surface and is _great_ for PR but where less than 1% of their employees actually work because most of staff work in sealed warehouses with _zero_ natural light ... https://www.businessinsider.com/amazon-warehouse-workers-share-their-horror-stories-2018-4

related to #8 Plants!

**Comment by Cleop** [comment]
I couldn't agree more. One solution I've found for this is by having a lightweight and moveable workspace at home (my ironing board!)

So in our small not very bright flat where the light moves from one window to another throughout the day I move myself to follow it! Being able to move yourself is advantageous not only for following light throughout the day but also so you don't have to block out the light if it ever comes at an angle where it's glaring on your screen.

![image](https://user-images.githubusercontent.com/16775804/47213311-7a93e980-d392-11e8-85e1-8462c213b495.png)

**Comment by nelsonic** [comment]
Closing as no further action required. ✅ 
Hope you are all well @Cleop ☀️ 🪴
