### ISSUE TITLE
Alternative Well-Being Fair - this weekend in Braga!

### ISSUE THREAD

**Issue by iteles** [dwyl/home#94]
This weekend is the alternative well-being fair in Braga

http://feiraalternativa.pt/
![image](https://user-images.githubusercontent.com/4185328/66151165-a85b5800-e60e-11e9-8092-7ddf8093f3e2.png)

There are workshops, seminars, exhibitors and crafts.
http://feiraalternativa.pt/feira-alternativa-porto/programa-porto/

Definitely worth a visit!

**Comment by nelsonic** [comment]
We went. It was good. 👍
