### ISSUE TITLE
Buy kitchen extractors

### ISSUE THREAD

**Issue by iteles** [dwyl/home#97]
We'll need to buy kitchen extractors and it would be great to get the electricians to wire them in directly rather than having less reliable electricians have to come in especially to install them (or to install them ourselves).

@nelsonic I know you've researched this before but I'm having trouble finding the issue.
I propose we:
+ [ ] Confirm the required measurements on-site tomorrow
+ [ ] Review requirements and research already done
+ [ ] 1 pomodoro of additional research
+ [ ] Make a decision on what to buy and whether to buy now or wait for November sales

**Comment by nelsonic** [comment]
@iteles https://github.com/dwyl/home/issues/53 😉

**Comment by iteles** [comment]
:+1: Thank you!
